### ISSUE TITLE
issue with creating pool (getting error - "The python f5-sdk module is required")

### ISSUE THREAD

**Issue by nelsoni2** [F5Networks/f5-ansible#757] opened 2018-06-16 13:41 UTC
Hi, I have installed f5-SDK(Version: 3.0.16) on my Mac but still, I am getting   the below error while executing  (lots-of-nodes.yaml)                                                                                                                                                "failed: [10.98.14.91 -> localhost] (item={'name': 'prdmarketing12', 'host': '10.40.20.112'}) => {"changed": false, "item": {"host": "10.40.20.112", "name": "prdmarketing12"}, "msg": "The python f5-sdk module is required"}"

**Comment by caphrim007** [comment] 2018-06-17 04:30
@nelsoni2 

9 times out of 10 this means that you're running Ansible from a virtualenv and havent correctly configured your ansible_python_interpreter to point to the place you installed the f5-sdk.

**Comment by caphrim007** [comment] 2018-06-17 15:33
@nelsoni2 are you running ansible from a virtualenv?

**Comment by nelsoni2** [comment] 2018-06-18 03:32
not sure but i am running on my mac

**Comment by caphrim007** [comment] 2018-06-18 03:42
@nelsoni2 show me your playbook

**Comment by nelsoni2** [comment] 2018-06-18 03:45
---

- name: Create a pool
  hosts: bigip
  connection: local

  tasks:
      - name: Create a node
        bigip_node:
            server: "bigip"
            user: "COF5ADMN01"
            password: "EIbz6yUjRiAb-ep"
            name: "nl"
            monitor_type: "http"
            host: "10.1.1.1"
            lb_method: "ratio-member"
            validate_certs: "false"

**Comment by nelsoni2** [comment] 2018-06-18 03:47
Thanks for your quick help and response 👍 
here i am able to ping my f5 device

$ ansible -m ping all
 [WARNING]: Found both group and host with same name: local

127.0.0.1 | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
local | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
10.98.14.91 | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}

**Comment by caphrim007** [comment] 2018-06-18 03:50
@nelsoni2 what is the output of `which python` ?

**Comment by nelsoni2** [comment] 2018-06-18 03:56
Here is the output

$ which python
/usr/local/bin/python

**Comment by caphrim007** [comment] 2018-06-18 03:58
@nelsoni2 you likely need to change your ansible_python_interpreter then because Ansible defaults to looking for it at `/usr/bin/python`

You can do this in your inventory file for your host. In your case you have a host or a group named `bigip` so you can specify the ansible_python_interpreter to use like this

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/inventory/hosts.example#L20

**Comment by caphrim007** [comment] 2018-06-18 03:59
presumably /usr/local/bin/python is also the python that has the f5-sdk installed

**Comment by nelsoni2** [comment] 2018-06-18 04:16
you mean to say like this (hosts) file: 

[bigip]
10.98.14.91 

[bigip:vars]
ansible_user=COF5ADMN01 
ansible_ssh_pass=EIbz6yUjRiAb-ep

[local]
127.0.0.1

[local:vars]
ansible_connection=local

[local]
local ansible_python_interpreter=/usr/local/bin/python

**Comment by caphrim007** [comment] 2018-06-18 04:17
@nelsoni2 no, like this

[bigip]
10.98.14.91 ansible_python_interpreter=/usr/local/bin/python

**Comment by nelsoni2** [comment] 2018-06-18 04:19
Oh sure, is this fine?

[bigip]
10.98.14.91 ansible_python_interpreter=/usr/local/bin/python

[bigip:vars]
ansible_user=COF5ADMN01 
ansible_ssh_pass=EIbz6yUjRiAb-ep

[local]
127.0.0.1

[local:vars]
ansible_connection=local

[local]
local ansible_python_interpreter=/usr/local/bin/python

**Comment by caphrim007** [comment] 2018-06-18 04:20
@nelsoni2 yeah try that

**Comment by caphrim007** [comment] 2018-06-18 04:28
@nelsoni2 the error is self-describing.

you're specifying an `lb_method` parameter to a module that doesnt support the `lb_method` parameter.

**Comment by nelsoni2** [comment] 2018-06-18 04:35
lets try 👍 

---

- name: Create a vip
  hosts: bigip
  connection: local

  tasks:
      - name: Create a VIP
        bigip_virtual_server:
            description: foo-vip
            destination: 172.16.10.108
            password: EIbz6yUjRiAb-ep
            name: vip-1
            pool: none
            port: 80
            server: bigip
            snat: Automap
            user: COF5ADMN01
            all_profiles:
                 - http
                 - clientssl
            validate_certs: no
        delegate_to: localhost

**Comment by nelsoni2** [comment] 2018-06-18 04:37
here also some issue:(i have installed suds)

$ pip install bigsuds
Requirement already satisfied: bigsuds in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.0.6)
Requirement already satisfied: suds-jurko>=0.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from bigsuds) (0.6)
z001nrr@34363bcd5bc0 /etc/ansible (devel)
$ ansible-playbook f5_info.yml
 [WARNING]: Found both group and host with same name: local


PLAY [Create a vip] *******************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************
ok: [10.98.14.91]

TASK [Create a VIP] *******************************************************************************************************************************************************
fatal: [10.98.14.91 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "the python bigsuds module is required"}
	to retry, use: --limit @/private/etc/ansible/f5_info.retry

PLAY RECAP ****************************************************************************************************************************************************************
10.98.14.91                : ok=1    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment] 2018-06-18 04:39
@nelsoni2 it says its installed at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

is this the same version of python that you have installed at /usr/local/bin/python?

what is the output of `/usr/local/bin/python -V`

**Comment by nelsoni2** [comment] 2018-06-18 04:40
here is the output:

$ /usr/local/bin/python -V
Python 2.7.15

**Comment by caphrim007** [comment] 2018-06-18 04:40
you dont have bigsuds installed in the correct python.

**Comment by nelsoni2** [comment] 2018-06-18 04:42
do I need to change the path?

**Comment by caphrim007** [comment] 2018-06-18 04:45
you need to pick a python version and stick with it.

You have at least two installed through some means. One is in your system libraries (python 3.6) and one is in /usr/local/bin (2.7). These different python installations **can not** share libraries between them.

So you need to decide to use one or the other, and then make sure that when you install python modules (via pip, or the equivalent command) that you are using the correct `pip` for your python installation

The `pip` in your path seems to be pointing to the python 3.6 installation. There should therefore be another `pip` command, perhaps in /usr/local/bin, that can be used to install dependencies for the python 2.7 install.

**Comment by nelsoni2** [comment] 2018-06-18 05:45
thanks will try

**Comment by nelsoni2** [comment] 2018-06-18 10:54
Now I am getting different error 👍 
$ ansible-playbook f5_info.yml 
 [WARNING]: Found both group and host with same name: local


PLAY [Create a vip] ************************************************************

TASK [Gathering Facts] *********************************************************
ok: [10.98.14.91]

TASK [Create a VIP] ************************************************************
[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more
 information. This feature will be removed in version 2.9. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for 
more information. This feature will be removed in version 2.9. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for 
more information. This feature will be removed in version 2.9. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'validate_certs' is deprecated. See the module 
docs for more information. This feature will be removed in version 2.9. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
fatal: [10.98.14.91 -> localhost]: FAILED! => {"changed": false, "msg": "Unable to connect to bigip on port 443. Is \"validate_certs\" preventing this?"}
	to retry, use: --limit @/private/etc/ansible/f5_info.retry

PLAY RECAP *********************************************************************
10.98.14.91                : ok=1    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment] 2018-06-18 14:15
@nelsoni2 this is always caused by incorrectly specifying the host name or IP address to the bigip in your `server` parameter.

In your playbook you have specified `bigip`, but that name is not resolvable in your DNS or hosts file.

You need to specify the variable "{{ ansible_host }}" so that you can use the IP address of the named host "bigip".

Your server line needs to be changed to the following

`server: "{{ ansible_host }}"`

You should also verify that you can curl the bigip before you use it. Oftentimes the bigip will be listening on a different port if you are running it in a cloud environment.

curl -k -u admin:admin https://IP/mgmt/tm/sys

Replace "IP" with the address of your bigip and "admin:admin" with your username and password for connecting to the bigip.

A calid Jon response should be returned

**Comment by nelsoni2** [comment] 2018-06-18 14:35
no luck executing the below yml.

---

- name: Create a vip
  hosts: bigip
  connection: local

  tasks:
      - name: Create a VIP
        bigip_virtual_server:
            description: foo
            destination: 172.16.10.108
            password: EIbz6yUjRiAb-ep
            name: vip-1
            pool: none
            port: 443
            server: "{{ ansible_host }}"
            snat: Automap
            user: COF5ADMN01
            all_profiles:
                 - http
                 - clientssl
            validate_certs: false
        delegate_to: localhost

**Comment by nelsoni2** [comment] 2018-06-18 14:37
here is the error:

$ ansible-playbook f5_info.yml 
 [WARNING]: Found both group and host with same name: local


PLAY [Create a vip] ************************************************************

TASK [Gathering Facts] *********************************************************
ok: [10.98.14.91]

TASK [Create a VIP] ************************************************************
[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more
 information. This feature will be removed in version 2.9. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for 
more information. This feature will be removed in version 2.9. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for 
more information. This feature will be removed in version 2.9. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'validate_certs' is deprecated. See the module 
docs for more information. This feature will be removed in version 2.9. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
fatal: [10.98.14.91 -> localhost]: FAILED! => {"changed": false, "msg": "Unable to connect to localhost on port 443. Is \"validate_certs\" preventing this?"}
	to retry, use: --limit @/private/etc/ansible/f5_info.retry

PLAY RECAP *********************************************************************
10.98.14.91                : ok=1    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment] 2018-06-18 15:18
@nelsoni2 can you curl the url that i mentioned?

**Comment by caphrim007** [comment] 2018-06-19 02:31
@nelsoni2 correction, change your server line to say `server: "{{ inventory_hostname }}"`. I miss-advised you there because your hosts "name", as known by ansible, is the IP address name.

**Comment by nelsoni2** [comment] 2018-06-19 04:18
Now its working fine ,Thank you so much Tim, i appreciated you help

**Comment by caphrim007** [comment] 2018-06-19 04:18
glad to hear. closing issue

**Comment by nelsoni2** [comment] 2018-06-19 04:19
You can thanks again

**Closed by caphrim007** 2018-06-19 04:18 UTC
Labels: not-a-bug
