### ISSUE TITLE
Missing order suboption for pools in bigip_gtm_wide_ip module

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-ansible#1597] opened 2019-12-31 19:01 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
`bigip_gtm_wide_ip`

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /home/erjac77/dev/ansible_live_f5/ansible.cfg
  configured module search path = ['/home/erjac77/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/erjac77/.local/lib/python3.6/site-packages/ansible
  executable location = /home/erjac77/.local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### PYTHON VERSION

```
Python 3.6.9
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### OS / ENVIRONMENT

Ubuntu 18.04.3 LTS

##### SUMMARY

`pools` option in `bigip_gtm_wide_ip` module doesn't support `order` suboption (it does support `ratio` however).

##### STEPS TO REPRODUCE

Example playbook:

```
---
- name: 
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Manage GTM WideIP
      bigip_gtm_wide_ip:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ http_user }}"
          password: "{{ http_pass }}"
          server_port: "{{ http_port }}"
          validate_certs: false
        name: test.localhost
        pool_lb_method: round-robin
        pools:
          - name: test_http_pool
            order: 3
            ratio: 100
        type: a
        state: present
      delegate_to: localhost
```

##### EXPECTED RESULTS

`bigip_gtm_wide_ip` module should support `order` suboption for `pools`. In this example, `order` should be set to 3.

##### ACTUAL RESULTS

`order` suboption is ignored and set to 0 (default). The `ratio` option is set correctly.

```
erjac77@xxx:~/dev/test-wideip-order$ ansible-playbook -i hosts site.yml -vvvv
ansible-playbook 2.9.1
  config file = None
  configured module search path = ['/home/erjac77/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/erjac77/.local/lib/python3.6/site-packages/ansible
  executable location = /home/erjac77/.local/bin/ansible-playbook
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /home/erjac77/dev/test-wideip-order/hosts as it did not pass its verify_file() method
script declined parsing /home/erjac77/dev/test-wideip-order/hosts as it did not pass its verify_file() method
auto declined parsing /home/erjac77/dev/test-wideip-order/hosts as it did not pass its verify_file() method
Parsed /home/erjac77/dev/test-wideip-order/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/erjac77/.local/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: site.yml ********************************************************************************************************************************************
Positional arguments: site.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/erjac77/dev/test-wideip-order/hosts',)
forks: 5
1 plays in site.yml

PLAY [all] ****************************************************************************************************************************************************
META: ran handlers

TASK [Manage GTM WideIP] **************************************************************************************************************************************
task path: /home/erjac77/dev/test-wideip-order/site.yml:8
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: erjac77
<localhost> EXEC /bin/sh -c 'echo ~erjac77 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930 `" && echo ansible-tmp-1577818083.0483913-228998151825930="` echo /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930 `" ) && sleep 0'
Using module file /home/erjac77/.local/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_gtm_wide_ip.py
<localhost> PUT /home/erjac77/.ansible/tmp/ansible-local-47143kjdlqvcz/tmpjozber_3 TO /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930/AnsiballZ_bigip_gtm_wide_ip.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930/ /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930/AnsiballZ_bigip_gtm_wide_ip.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930/AnsiballZ_bigip_gtm_wide_ip.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/erjac77/.ansible/tmp/ansible-tmp-1577818083.0483913-228998151825930/ > /dev/null 2>&1 && sleep 0'
ok: [xxx -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aliases": null,
            "irules": null,
            "last_resort_pool": null,
            "name": "test.localhost",
            "partition": "Common",
            "pool_lb_method": "round-robin",
            "pools": [
                {
                    "name": "test_http_pool",
                    "order": 3,
                    "ratio": 100
                }
            ],
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "xxx",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "xxx",
                "validate_certs": false
            },
            "state": "present",
            "type": "a"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************************
xxx : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

On the BIG-IP:
```
xxx@(xxx)(cfg-sync Standalone)(Active)(/Common)(tmos)# list gtm wideip a test.localhost
gtm wideip a test.localhost {
    pools {
        test_http_pool {
            order 0
            ratio 100
        }
    }
}
```

**Comment by DerrickTJ** [comment] 2020-01-03 14:56
The only option for pools is name and ratio. If you want another option, this should be a feature request. The documentation doesn't say anything about "order" being usable.

**Comment by wojtek0806** [comment] 2020-01-03 16:04
FMFA-413

**Comment by erjac77** [comment] 2020-01-03 16:10
Hi @DerrickTJ,

I disagree, the option is mentioned in the doc. Look here:

https://clouddocs.f5.com/api/icontrol-rest/APIRef_tm_gtm_wideip_a.html

```
/pools/order | integer |   | optional | read/write | Specifies the order of this pool in relation to other pools attached to this Wide IP. Pool order is significant when the Global Availability load balancing method is utilized.
```

This option is very important to us. We use it to manually change the order of our pools, during a maintenance or an outage for example.

Thank you.

**Comment by DerrickTJ** [comment] 2020-01-03 16:42
That is a feature request non the less. Not a bug with the ansible module.

**Comment by erjac77** [comment] 2020-01-03 17:50
Of course. I've changed the issue type shortly after your first post.

Thank you again.

**Comment by wojtek0806** [comment] 2020-04-03 10:43
merged with: https://github.com/F5Networks/f5-ansible/pull/1696

**Closed by wojtek0806** 2020-04-03 10:43 UTC
Labels: enhancement, in-action
