### ISSUE TITLE
Client SSL Profile - Key Not Found

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1440] opened 2019-08-06 14:30 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_profile_client_ssl

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = /Users/DerrickTJ/Documents/GitHub/DerrickTJ/DJ_TestProject/ansible.cfg
  configured module search path = ['/Users/DerrickTJ/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/DerrickTJ/Documents/Ansible28/lib/python3.7/site-packages/ansible
  executable location = /Users/DerrickTJ/Documents/Ansible28/bin/ansible
  python version = 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)]
```

##### PYTHON VERSION

```
Python 3.7.2
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.3
  Build       0.0.6
  Edition     Point Release 3
  Date        Mon Mar 25 17:15:27 PDT 2019
```

##### ROLE VERSION

Well... this was not what we wanted.
```
$ ansible-galaxy info f5devcentral.f5ansible
ERROR! Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL certificate for galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056). 

```

##### CONFIGURATION
gathering = explicit

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The requested key (/Common/Wildcard.name.net_expires_2020.key) was not found.

##### STEPS TO REPRODUCE

```
   - name: Create a client SSL profile with a cert/key/chain setting
     bigip_profile_client_ssl:
       state: present
       name: wildcard.hy-vee.net-clientssl
       cert_key_chain:
         - cert: Wildcard.name.net_expires_2020
           key: Wildcard.name.net_expires_2020
           chain: Wildcard.name.net_expires_2020
```

##### EXPECTED RESULTS
Create the SSL Client Profile

##### ACTUAL RESULTS

/config/filestore/files_d/Common_d/certificate_key_d/
:Common:Wildcard.name.net_expires_2020.key_63717_1

```
ASK [Create a client SSL profile with a cert/key/chain setting] **********************************************************************************************************************************************************************
task path: /Users/DerrickTJ/Documents/GitHub/DerrickTJ/DJ_TestProject/testplaybook.yaml:18
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: DerrickTJ
<localhost> EXEC /bin/sh -c 'echo ~DerrickTJ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628 `" && echo ansible-tmp-1565101538.409843-71259515511628="` echo /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628 `" ) && sleep 0'
Using module file /Users/DerrickTJ/Documents/Ansible28/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_profile_client_ssl.py
<localhost> PUT /Users/DerrickTJ/.ansible/tmp/ansible-local-156789es0z69l/tmp6iq31oki TO /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628/AnsiballZ_bigip_profile_client_ssl.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628/ /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628/AnsiballZ_bigip_profile_client_ssl.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/DerrickTJ/Documents/Ansible28/bin/python3 /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628/AnsiballZ_bigip_profile_client_ssl.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/DerrickTJ/.ansible/tmp/ansible-tmp-1565101538.409843-71259515511628/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/80/qxqt__d92fz5dknpxl46xk9n02zpz9/T/ansible_bigip_profile_client_ssl_payload_jf72qsrj/__main__.py", line 1102, in main
    results = mm.exec_module()
  File "/var/folders/80/qxqt__d92fz5dknpxl46xk9n02zpz9/T/ansible_bigip_profile_client_ssl_payload_jf72qsrj/__main__.py", line 872, in exec_module
    changed = self.present()
  File "/var/folders/80/qxqt__d92fz5dknpxl46xk9n02zpz9/T/ansible_bigip_profile_client_ssl_payload_jf72qsrj/__main__.py", line 893, in present
    return self.update()
  File "/var/folders/80/qxqt__d92fz5dknpxl46xk9n02zpz9/T/ansible_bigip_profile_client_ssl_payload_jf72qsrj/__main__.py", line 918, in update
    self.update_on_device()
  File "/var/folders/80/qxqt__d92fz5dknpxl46xk9n02zpz9/T/ansible_bigip_profile_client_ssl_payload_jf72qsrj/__main__.py", line 971, in update_on_device
    raise F5ModuleError(response['message'])

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "advertised_cert_authority": null,
            "allow_expired_crl": null,
            "allow_non_ssl": null,
            "auth_provider": null,
            "cert_auth_depth": null,
            "cert_key_chain": [
                {
                    "cert": "Wildcard.name.net_expires_2020",
                    "chain": "Wildcard.name.net_expires_2020",
                    "key": "Wildcard.name.net_expires_2020"
                }
            ],
            "ciphers": null,
            "client_auth_crl": null,
            "client_auth_frequency": null,
            "client_certificate": null,
            "name": "wildcard.name.net-clientssl",
            "options": null,
            "parent": "/Common/clientssl",
            "partition": "Common",
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "LTM-F5-001",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "renegotiation": null,
            "retain_certificate": null,
            "secure_renegotiation": null,
            "server": null,
            "server_name": null,
            "server_port": null,
            "sni_default": null,
            "sni_require": null,
            "state": "present",
            "strict_resume": null,
            "transport": null,
            "trusted_cert_authority": null,
            "user": null,
            "validate_certs": null
        }
    },
    "msg": "01070277:3: The requested key (/Common/Wildcard.name.net_expires_2020.key) was not found."
}

```

**Comment by wojtek0806** [comment] 2019-08-07 09:44
@DerrickTJ 
The error comes from the BIGIP, verify the key exists in the configuration, some tmsh output would help here, the file can be in filestore but if it is not referenced in config then you will run into this error

**Comment by DerrickTJ** [comment] 2019-08-07 14:16
Do you know what commands to run? I can build the SSL Profile manual with no issues.

**Comment by DerrickTJ** [comment] 2019-08-07 17:39
I've replaced sensitive information with '*' Let me know if you need something in those details. The ltm client profile down below is what I created manually in the GUI.
```
sys file ssl-cert Wildcard.name.net_expires_2020.crt {
    create-time 2019-08-06:06:45:25
}
sys file ssl-key Wildcard.name.net_expires_2020.key {
    create-time 2019-08-06:06:44:43
}
sys crypto cert Wildcard.name.net_expires_2020.crt {
    *
}
sys crypto key Wildcard.name.net_expires_2020.key {
    *
}
ltm profile client-ssl wildcard.name.net-clientssl {
    app-service none
    cert-key-chain {
        Wildcard.name.net_expires_2020_Wildcard.name.net_expires_2020_0 {
            cert Wildcard.name.net_expires_2020.crt
            chain Wildcard.name.net_expires_2020.crt
            key Wildcard.name.net_expires_2020.key
        }
    }
    defaults-from clientssl
    inherit-ca-certkeychain true
    inherit-certkeychain false
}
```

**Comment by DerrickTJ** [comment] 2019-08-07 17:40
@wojtek0806 
I've replaced sensitive information with '*' Let me know if you need something in those details. The ltm client profile down below is what I created manually in the GUI.
```
sys file ssl-cert Wildcard.name.net_expires_2020.crt {
    create-time 2019-08-06:06:45:25
}
sys file ssl-key Wildcard.name.net_expires_2020.key {
    create-time 2019-08-06:06:44:43
}
sys crypto cert Wildcard.name.net_expires_2020.crt {
    *
}
sys crypto key Wildcard.name.net_expires_2020.key {
    *
}
ltm profile client-ssl wildcard.name.net-clientssl {
    app-service none
    cert-key-chain {
        Wildcard.name.net_expires_2020_Wildcard.name.net_expires_2020_0 {
            cert Wildcard.name.net_expires_2020.crt
            chain Wildcard.name.net_expires_2020.crt
            key Wildcard.name.net_expires_2020.key
        }
    }
    defaults-from clientssl
    inherit-ca-certkeychain true
    inherit-certkeychain false
}
```

**Comment by focrensh** [comment] 2019-08-07 18:10
I just tested this on 14.1.0.5 with the same error. On v13 it worked as expected. @wojtek0806 ill send you the details.

**Comment by wojtek0806** [comment] 2019-09-23 12:38
@focrensh i am still waiting for the reproduction you have created for this and more information

**Comment by wojtek0806** [comment] 2019-10-14 12:54
@DerrickTJ  @focrensh 

Test system:
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.3
  Build       0.0.6
  Edition     Point Release 3
  Date        Mon Mar 25 17:15:27 PDT 2019
```
I have ran the series of these playbooks:
https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_profile_client_ssl/tasks/issue-00418.yaml
The profile is created successfully (I have stepped through the test run to verify this manually):
```
root@(v14-1)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm profile client-ssl issue-00418
ltm profile client-ssl issue-00418 {
    app-service none
    cert-key-chain {
        issue-00418-cert1 {
            cert issue-00418-cert1.crt
            chain issue-00418-chain1.crt
            key issue-00418-key1.key
        }
    }
    defaults-from clientssl
    inherit-ca-certkeychain true
    inherit-certkeychain false
}
```
The run results:
```
PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
bigip_14                   : ok=12   changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

I see no issue, marking this as not reproducible

**Comment by wojtek0806** [comment] 2019-10-14 13:00
we can revisit if a reliable reproduction is provided

**Comment by mbystrzak** [comment] 2019-10-14 13:29
I'm having this same issue in 14.1.2, but inly when trying to assign a cert created from .pfx format. I'm happy to share my repro information with you, I was hoping for a fix on this one. It's possible I'm doing something wrong, but I don't believe I am. It won't be today however, I'm one of the fortunate ones who have Columbus day off :) I'll repro and provide the info in the morning tomorrow.

**Comment by wojtek0806** [comment] 2019-10-14 14:23
how is the PFX file being imported? is it via GUI or using bigip_ssl_cert/bigip_ssl_key module?? most likely your pfx file is failing to import hence the system does not register it in file-store.

**Comment by DerrickTJ** [comment] 2019-10-14 16:01
I imported my PFX within the GUI when I was having the issue. I haven't tried to do this again since I made the ticket. I will retest again tomorrow if time permits and provide more information.

**Comment by mbystrzak** [comment] 2019-10-14 16:10
Iv the imported through the gui at this point. I've verified the key and chain exists on the box through the gui and the cli just to be sure. That same cert can be applied to an ssl profile through the gui so it has to exist but through the client profile module in ansible, no dice.

**Comment by focrensh** [comment] 2019-11-18 19:50
Just tested and hit the issue in 2.9. @wojtek0806 sent you an email with the task and test crt/key i used.

**Comment by mbystrzak** [comment] 2019-12-09 18:25
Thanks Gents!

**Comment by mbystrzak** [comment] 2019-12-16 19:32
Guys. I'm still having the same problem. I downloaded and installed the daily build after you put up the correction and it's still not working. I verified that I'm using the devel modules.

The problem, I'm finding, doesn't just pop up when you don't define a key file with a ".key" suffix to the name, but also becomes a problem with the certificate if you don't apply the ".crt" suffix to the name.

If you have a file mycertificate.crt and a corresponding keyfile named mycertificate.key all is well in the kingdom. BUT as soon as you try to reference a cert or key file which doesn't have those suffix's the job fails. 

When I put a .pfx cert on my system and name it mycertificate.mydomain.com it creates a cert and a key in the system, both of which have then name mycertificate.mydomain.com just like that with no suffix, as verified by show sys crypto cert and show sys crypto key. When you try to assign a cert added to the system without the .crt / .key suffix the ansible job fails. 

Let me know if this makes sense or if you have questions. It seems as of right now the only way this module works is if you have a separate cert and key file, and when uploaded to the system you name the with the .crt / .key suffix's respectively.

Thanks

**Comment by mbystrzak** [comment] 2019-12-16 19:44
Another note to add on to my last post.

The same issue exists when you go to add the "chain". If the chain does not have .crt in the name, the playbook fails.

I don't personally ever use .crt or .key in any name, especially given the PFX format where it's all combined into one.

I did extract a version of each of these files for the cert, the chain cert, and the key with the appropriate suffixes and the playbook succeeds. This is obviously not going to scale.

**Comment by wojtek0806** [comment] 2019-12-16 20:29
Use the appropriate option:
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_profile_client_ssl.py#L72

**Comment by mbystrzak** [comment] 2019-12-16 20:57
Is the proper syntax as follows:
---
    cert_key_chain:
      - cert: bigip_ssl_cert1
        key: bigip_ssl_key1
        chain: bigip_ssl_cert1
        true_names: yes

This doesn't appear to be working for me. If I move true_names out to the cert_key_chain level I get a  really nasty error. Otherwise I get the same error I've been getting.

**Comment by mbystrzak** [comment] 2019-12-19 13:15
Anything on my last post regarding syntax?

**Comment by wojtek0806** [comment] 2020-01-03 16:59
the syntax is ok, i have uploaded cert/key without .key/.crt and the module recognises these correctly

**Comment by wojtek0806** [comment] 2020-01-03 17:01
@focrensh as discussed reopening awaiting your repro feedback

**Comment by mbystrzak** [comment] 2020-02-03 16:36
Curious on whether or not there has been any progress on this? I'd really like to use it for certificate automation but I'm struggling to do it because of this. I'm open to work-arounds as well.

**Comment by focrensh** [comment] 2020-02-06 20:35
Thank you for your persistence on this. I was able to repro something similar just now without pk12 certs. Updating our internal tracking for prioritization based on this.


FMFA-430. Will update ASAP on findings.

**Comment by focrensh** [comment] 2020-02-06 22:57
Team is working on merging a fix now. Will update here once in our daily build.

**Comment by wojtek0806** [comment] 2020-02-07 00:20
corrected the previous solution slightly:
https://github.com/F5Networks/f5-ansible/pull/1642 should be fixed now

**Closed by wojtek0806** 2020-02-07 00:20 UTC
Labels: backlog, bug

**Comment by mbystrzak** [comment] 2020-02-07 01:27
Great I'll pull the daily and give it a go in the morning. I'll let you know if I continue to have issues. Thanks a bunch for your help. This is a big thing for our organization.

**Comment by mbystrzak** [comment] 2020-02-07 16:34
This worked!!!!

This is officially closed from my side. You guys are gods among men! When can I expect this to hit a regular release?

**Comment by focrensh** [comment] 2020-02-07 17:08
Looking at around 2-4 weeks for a few other updates to make it in.

**Comment by DerrickTJ** [comment] 2020-02-07 19:01
sweeeeeeet

Thanks everyone!

**Comment by sanjaypalande** [comment] 2021-11-14 22:23
I'm getting the similar issues with creating clients sleep profile. How can I download the build that has fix for this? Any help would he greatly appreciated
