### ISSUE TITLE
bigip_data_group always return "changed=true" when partition is other than "common"

### ISSUE THREAD

**Issue by mateusz5** [F5Networks/f5-ansible#1210] opened 2019-02-07 14:23 UTC
Moved from https://github.com/ansible/ansible/issues/50604 as requested by @wojtek0806.

##### SUMMARY
When using bigip_data_group module to add data_group on F5 LTM partition other than "Common", result is always "changed=true".
When adding on "Common" partition, I get "changed=false" if data_group is already there.

Looks like problem is limited to "ip" type of data_group ("integer" or "string" are OK)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
bigip_data_group

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /.../ansible.cfg
  configured module search path = [u'/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /.../lib/python2.7/site-packages/ansible
  executable location = /.../bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```
Also, tested on ansible 2.6.0
f5_sdk = 3.0.20 (also tested on 3.0.16)

##### CONFIGURATION
```
DEFAULT_FILTER_PLUGIN_PATH(/.../ansible.cfg) = [u'/.../filter_plugins']
DEFAULT_HOST_LIST(/.../ansible.cfg) = [u'/.../net-inventory']
DEFAULT_ROLES_PATH(/.../ansible.cfg) = [u'/.../roles']
HOST_KEY_CHECKING(/.../ansible.cfg) = False
```

##### OS / ENVIRONMENT
F5 LTM: BIG-IP 12.1.3.5 Build 0.0.10 Point Release 5
Using partitions + separate route domains

##### STEPS TO REPRODUCE
```
---
- name: F5 BIG-IP datagroups configuration management
  hosts: all

  connection: network_cli
  gather_facts: no

  tasks:

    - name: Update datagroups - Common
      bigip_data_group:
        server: server
        password: pass
        user: user
        internal: "yes"
        partition: 'Common'
        name: 'data_group_Common'
        type: 'ip'
        records:
          - key: '10.10.10.0/24'
            value: ''
          - key: '20.20.20.0/24'
            value: ''
        state: present
        validate_certs: "no"
      ignore_errors: True
      delegate_to: localhost

    - name: Update datagroups - Other
      bigip_data_group:
        server: server
        password: pass
        user: user
        internal: "yes"
        partition: 'Other'
        name: 'data_group_Other'
        type: 'ip'
        records:
          - key: '10.10.10.0/24'
            value: ''
          - key: '20.20.20.0/24'
            value: ''
        state: present
        validate_certs: "no"
      ignore_errors: True
      delegate_to: localhost
```

##### EXPECTED RESULTS
```
AFTER FIRST RUN (datagroups not present yet on server):

PLAY [F5 BIG-IP datagroups configuration management] *******************************************************************************************************************************************************

TASK [Update datagroups - Common] **************************************************************************************************************************************************************************
changed: [server -> localhost]

TASK [Update datagroups - TEST_PL4] ************************************************************************************************************************************************************************
changed: [server -> localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
server  : ok=2    changed=2    unreachable=0    failed=0   

AFTER ANOTHER RUN, "ok:" expected, as no changes were made
```
##### ACTUAL RESULTS

```
AFTER ANOTHER RUN:

PLAY [F5 BIG-IP datagroups configuration management] *******************************************************************************************************************************************************

TASK [Update datagroups - Common] **************************************************************************************************************************************************************************
ok: [server -> localhost]

TASK [Update datagroups - TEST_PL4] ************************************************************************************************************************************************************************
changed: [server -> localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
server   : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by wojtek0806** [comment] 2019-02-13 14:22
@mateusz5 I have ran tests against current devel and this issue is not reproducible:

- 1st Run
```
TASK [Create Other partition] *********************************************************************************************************************************************************************************************************************************************
changed: [bigip_12] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "description": null,
            "name": "Other",
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "SANITIZED",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "route_domain": null,
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    }
}

TASK [Create datagroups - Common] *****************************************************************************************************************************************************************************************************************************************
changed: [bigip_12] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "delete_data_group_file": null,
            "description": null,
            "external_file_name": null,
            "internal": true,
            "name": "data_group_Common",
            "partition": "Common",
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "SANITIZED",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "records": [
                {
                    "key": "10.10.10.0/24",
                    "value": ""
                },
                {
                    "key": "20.20.20.0/24",
                    "value": ""
                }
            ],
            "records_src": null,
            "separator": ":=",
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "type": "ip",
            "user": null,
            "validate_certs": null
        }
    },
    "records": [
        {
            "data": "",
            "name": "10.10.10.0/24"
        },
        {
            "data": "",
            "name": "20.20.20.0/24"
        }
    ],
    "type": "ip"
}

TASK [Create datagroups - Other] ******************************************************************************************************************************************************************************************************************************************
changed: [bigip_12] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "delete_data_group_file": null,
            "description": null,
            "external_file_name": null,
            "internal": true,
            "name": "data_group_Other",
            "partition": "Other",
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "SANITIZED",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "records": [
                {
                    "key": "10.10.10.0/24",
                    "value": ""
                },
                {
                    "key": "20.20.20.0/24",
                    "value": ""
                }
            ],
            "records_src": null,
            "separator": ":=",
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "type": "ip",
            "user": null,
            "validate_certs": null
        }
    },
    "records": [
        {
            "data": "",
            "name": "10.10.10.0/24"
        },
        {
            "data": "",
            "name": "20.20.20.0/24"
        }
    ],
    "type": "ip"
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************
bigip_12                   : ok=3    changed=3    unreachable=0    failed=0   
```

- 2nd run:
```
TASK [Create datagroups - Common - Idempotent Test] ***********************************************************************************************************************************************************************************************************************
ok: [bigip_12] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "delete_data_group_file": null,
            "description": null,
            "external_file_name": null,
            "internal": true,
            "name": "data_group_Common",
            "partition": "Common",
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "SANITIZED",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "records": [
                {
                    "key": "10.10.10.0/24",
                    "value": ""
                },
                {
                    "key": "20.20.20.0/24",
                    "value": ""
                }
            ],
            "records_src": null,
            "separator": ":=",
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "type": "ip",
            "user": null,
            "validate_certs": null
        }
    }
}

TASK [Create datagroups - Other - Idempotent Test] ************************************************************************************************************************************************************************************************************************
ok: [bigip_12] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "delete_data_group_file": null,
            "description": null,
            "external_file_name": null,
            "internal": true,
            "name": "data_group_Other",
            "partition": "Other",
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "SANITIZED",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "records": [
                {
                    "key": "10.10.10.0/24",
                    "value": ""
                },
                {
                    "key": "20.20.20.0/24",
                    "value": ""
                }
            ],
            "records_src": null,
            "separator": ":=",
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "type": "ip",
            "user": null,
            "validate_certs": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************
bigip_12                   : ok=2    changed=0    unreachable=0    failed=0   
```
My playbooks:

- Used for first run:
```
---
- name: Start Tests
  gather_facts: no
  hosts: all
  connection: local

  vars:
    provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Create Other partition
      bigip_partition:
        name: Other
        state: present
        provider: "{{ provider }}"

    - name: Create datagroups - Common
      bigip_data_group:
        internal: "yes"
        partition: 'Common'
        name: 'data_group_Common'
        type: 'ip'
        records:
          - key: '10.10.10.0/24'
            value: ''
          - key: '20.20.20.0/24'
            value: ''
        state: present
        provider: "{{ provider }}"

    - name: Create datagroups - Other
      bigip_data_group:
        internal: "yes"
        partition: 'Other'
        name: 'data_group_Other'
        type: 'ip'
        records:
          - key: '10.10.10.0/24'
            value: ''
          - key: '20.20.20.0/24'
            value: ''
        state: present
        provider: "{{ provider }}"
```
- Used for second run:
```
---
- name: Start Tests
  gather_facts: no
  hosts: all
  connection: local

  vars:
    provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Create datagroups - Common - Idempotent Test
      bigip_data_group:
        internal: "yes"
        partition: 'Common'
        name: 'data_group_Common'
        type: 'ip'
        records:
          - key: '10.10.10.0/24'
            value: ''
          - key: '20.20.20.0/24'
            value: ''
        state: present
        provider: "{{ provider }}"

    - name: Create datagroups - Other - Idempotent Test
      bigip_data_group:
        internal: "yes"
        partition: 'Other'
        name: 'data_group_Other'
        type: 'ip'
        records:
          - key: '10.10.10.0/24'
            value: ''
          - key: '20.20.20.0/24'
            value: ''
        state: present
        provider: "{{ provider }}"
```

**Comment by wojtek0806** [comment] 2019-02-13 14:24
@mateusz5 in your repro playbook you are using deprecated way of configuring your connection, try using: 'provider' the same way i do, also `connection: local` Try running my playbooks on your machine and report back. for now I will close this issue as not reproducible and not a bug, if you can give me a working reproduction then we can revisit.

**Comment by mateusz5** [comment] 2019-02-18 14:26
@wojtek0806 I tried Your playbook and it end successfuly - "changed" only after first run, "ok" after running again.
However, I still get same wrong result when I try to add datagroup into my previously (manually) created partition.
So it seems like there is something in particular about that partition of mine.
There is a separate route-domain defined as default for it.
I'll do some more tests to see what is really the case.

**Comment by wojtek0806** [comment] 2019-02-18 16:22
ok let me know when you get more information and reproduction conditions and we can revisit this

**Comment by mateusz5** [comment] 2019-02-19 07:52
@wojtek0806 I did some tests - It seems that having different route-domain as default for partition is the problem (until you have 0 as default route domain for a partition "Other" you get propper result when creating data group - after switching default route domain to different than 0, you get "changed" each time):

Steps to reproduce (GUI):

1) create new partition:
- Partition Name: Other
- Partition Default Route Domain: 0

2) switch into that partition

3) create new route-domain:
- Name: Other
- ID: 10
- Strict Isolation: Enabled

4) go back to Partition configuration section (System  ››  Users : Partition List  ››  Other) and change "Partition Default Route Domain" from "0" to "10"

5) run ansible playbook to create data group in "Other" partition:

tasks:
  - name: Create datagroups - Other
    bigip_data_group:
      internal: "yes"
      partition: 'Other'
      name: 'DG_Other'
      type: 'ip'
      records:
        - key: '10.10.10.0/24'
          value: ''
        - key: '20.20.20.0/24'
          value: ''
      state: present
      provider: "{{ provider }}"

result: "changed"

6) run playbook again: result "changed" again

**Comment by mateusz5** [comment] 2019-02-19 10:25
It also seems that once You create data group while "Partition Default Route Domain" for partition "Other" is set to "0", and You then switch back to "10" playbook returns "OK".

So to fully reproduce the problem You need to create data group while "Partition Default Route Domain" for partition "Other" is set to "10". Then You get "CHANGED" each time you run playbook.

**Closed** 2019-02-20 22:27 UTC
Labels: bug-report, fails-on-devel
