### ISSUE TITLE
bigip_gtm_server server-type it suppose to by single-bigip not  standalone-bigip 

### ISSUE THREAD

**Issue by RequinBleu** [F5Networks/f5-ansible#539] opened 2017-12-19 16:45 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_gtm_server
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.6
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

The module require standalone-bigip but bigip need single-bigip so the module don't work.

you need to change:
at line 512:
'foundry-server-iron', 'netapp', 'standalone-bigip',
by 
'foundry-server-iron', 'netapp', 'single-bigip',

By the way in you exemple you need to change product by server-type

```
     bigip_gtm_server:
      server: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      datacenter: /Common/{{ item.datacenter }}
      server_type: standalone-bigip
      link_discovery: disabled
      virtual_server_discovery: disabled
      devices:
        - {'name': '{{fqdn}}', 'address': '{{ansible_host}}'}
     with_items: "{{spreadsheet_GTM}}"
     when: 
       - item.mgt_IP in ansible_host
       - item.do == "yes"
```

##### ACTUAL RESULTS

```
msg": "400 Unexpected Error: Bad Request for uri: https://x.x.x.x:443/mgmt/tm/gtm/server/~Common~hostname/\nText: u'{\"code\":400,\"message\":\"invalid property value \\\\\"product\\\\\":\\\\\"standalone-bigip\\\\\"\",\"errorStack\":[],\"apiError\":26214401}'"
```

**Comment by caphrim007** [comment] 2017-12-19 18:41
@RequinBleu no, it only needs to be line that in versions less than 13. I'm already aware of, and addressing this issue. server_type will remain `bigip`, the internals of the module will determine if it is standalone or redundant.

**Comment by RequinBleu** [comment] 2017-12-19 18:57
@caphrim007 the rest api call for product argument it suppose to be single-bigip not standalone-bigip. Yes it suppose use bigip and the internals of the module will determine if it is **single** or redundant. By the way I change the line and it work fine if I use single-bigip. but bigip still not work.

**Comment by RequinBleu** [comment] 2017-12-19 19:09
If I create in bigip gui I have this output:
`{
    "kind": "tm:gtm:server:serverstate",
    "name": "hostname",
    "partition": "Common",
    "fullPath": "/Common/hostname",
    "generation": 244,
    "selfLink": "https://localhost/mgmt/tm/gtm/server/~Common~hostname?ver=12.1.2",
    "datacenter": "/Common/dc1",
    "datacenterReference": {
        "link": "https://localhost/mgmt/tm/gtm/datacenter/~Common~dc1?ver=12.1.2"
    },
    "enabled": true,
    "exposeRouteDomains": "no",
    "iqAllowPath": "yes",
    "iqAllowServiceCheck": "yes",
    "iqAllowSnmp": "yes",
    "limitCpuUsage": 0,
    "limitCpuUsageStatus": "disabled",
    "limitMaxBps": 0,
    "limitMaxBpsStatus": "disabled",
    "limitMaxConnections": 0,
    "limitMaxConnectionsStatus": "disabled",
    "limitMaxPps": 0,
    "limitMaxPpsStatus": "disabled",
    "limitMemAvail": 0,
    "limitMemAvailStatus": "disabled",
    "linkDiscovery": "disabled",
    "monitor": "/Common/bigip ",
    **"product": "single-bigip",**
    "virtualServerDiscovery": "disabled",
    "addresses": [
        {
            "name": "x.x.x.x",
            "deviceName": "hostname",
            "translation": "none"
        }
    ],
    "virtualServersReference": {
        "link": "https://localhost/mgmt/tm/gtm/server/~Common~hostname/virtual-servers?ver=12.1.2",
        "isSubcollection": true
    }
}`

**Comment by caphrim007** [comment] 2017-12-19 19:14
@RequinBleu i know is supposed to be single and redundant. what i'm saying is that the module parameters will **not** be that. The reason it works when you change it is because you're using 12.x.

If you attempt to use that change on 13.x, it will fail.

**Comment by caphrim007** [comment] 2018-01-02 23:00
@RequinBleu 
I believe this issue has been recently fixed in the repo here. If you can check the updated code to make sure that it addresses the issue you were seeing, I'd appreciate it.

If the problem is still apparent, please file a new issue

**Closed** 2018-01-02 22:59 UTC
Labels: bug-report
