### ISSUE TITLE
Failing to add pool members due to "The specified pool does not exist"

### ISSUE THREAD

**Issue by ramganesh19** [F5Networks/f5-ansible#1967] opened 2021-02-12 21:39 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool_member

##### ANSIBLE VERSION

```
ansible 2.9.17
  config file = /home/rkanagas/stash/automation/ansible/F5/ansible.cfg
  configured module search path = [u'/home/rkanagas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]

```

##### PYTHON VERSION

```
Python 3.6.9
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.3.1
  Build       0.0.8
  Edition     Point Release 1
  Date        Wed Dec  9 19:13:18 PST 2020

```

##### OS / ENVIRONMENT

Ubuntu 18

##### SUMMARY

Failing to add pool members due to "The specified pool does not exist"

##### STEPS TO REPRODUCE

```
---

- name: Create a VIP, pool and pool members
  hosts: bigip
  connection: local
  vars:
    provider:
      password: <Password>
      server: <ip address>
      user: admin
      validate_certs: no
      server_port: 443                                                  

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
        monitors: http
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      loop:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02
      delegate_to: localhost    
      
    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 172.16.10.108
        name: vip-1
        pool: web
        port: 80
        snat: Automap
        profiles:
          - http
          - clientssl
      delegate_to: localhost

```

##### EXPECTED RESULTS

I am expecting the two pool members 10.10.10.10(web01) and 10.10.10.20(web02) added to pool web

##### ACTUAL RESULTS

$ ansible-playbook -i inventory/hosts playbook.yaml --check

PLAY [Create a VIP, pool and pool members] ******************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host bigip should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [bigip]

TASK [Create a pool] ****************************************************************************************************************************************
changed: [bigip]

TASK [Add members to pool] **********************************************************************************************************************************
failed: [bigip] (item={u'host': u'10.10.10.10', u'name': u'web01'}) => {"ansible_loop_var": "item", "changed": false, "item": {"host": "10.10.10.10", "name": "web01"}, "msg": "The specified pool does not exist"}
failed: [bigip] (item={u'host': u'10.10.10.20', u'name': u'web02'}) => {"ansible_loop_var": "item", "changed": false, "item": {"host": "10.10.10.20", "name": "web02"}, "msg": "The specified pool does not exist"}

PLAY RECAP **************************************************************************************************************************************************
bigip                      : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

```
ansible-playbook -i inventory/hosts playbook.yaml --check -vvvv
ansible-playbook 2.9.17
  config file = /home/rkanagas/stash/automation/ansible/F5/ansible.cfg
  configured module search path = [u'/home/rkanagas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
Using /home/rkanagas/stash/automation/ansible/F5/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/rkanagas/stash/automation/ansible/F5/inventory/hosts as it did not pass its verify_file() method
script declined parsing /home/rkanagas/stash/automation/ansible/F5/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /home/rkanagas/stash/automation/ansible/F5/inventory/hosts as it did not pass its verify_file() method
Parsed /home/rkanagas/stash/automation/ansible/F5/inventory/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: playbook.yaml *************************************************************************************************************************************
Positional arguments: playbook.yaml
check: True
become_method: sudo
inventory: (u'/home/rkanagas/stash/automation/ansible/F5/inventory/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in playbook.yaml

PLAY [Create a VIP, pool and pool members] ******************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
task path: /home/rkanagas/stash/automation/ansible/F5/playbook.yaml:3
<192.168.10.1> ESTABLISH LOCAL CONNECTION FOR USER: rkanagas
<192.168.10.1> EXEC /bin/sh -c 'echo ~rkanagas && sleep 0'
<192.168.10.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rkanagas/.ansible/tmp `"&& mkdir "` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883 `" && echo ansible-tmp-1613165481.15-15875-86772757958883="` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883 `" ) && sleep 0'
<bigip> Attempting python interpreter discovery
<192.168.10.1> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.10.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<192.168.10.1> PUT /home/rkanagas/.ansible/tmp/ansible-local-15868SEr1__/tmpoiOWBI TO /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883/AnsiballZ_setup.py
<192.168.10.1> EXEC /bin/sh -c 'chmod u+x /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883/ /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883/AnsiballZ_setup.py && sleep 0'
<192.168.10.1> EXEC /bin/sh -c '/usr/bin/python /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883/AnsiballZ_setup.py && sleep 0'
<192.168.10.1> EXEC /bin/sh -c 'rm -f -r /home/rkanagas/.ansible/tmp/ansible-tmp-1613165481.15-15875-86772757958883/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host bigip should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [bigip]
META: ran handlers

TASK [Create a pool] ****************************************************************************************************************************************
task path: /home/rkanagas/stash/automation/ansible/F5/playbook.yaml:15
<localhost> Using network group action bigip for bigip_pool
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rkanagas
<localhost> EXEC /bin/sh -c 'echo ~rkanagas && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rkanagas/.ansible/tmp `"&& mkdir "` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132 `" && echo ansible-tmp-1613165488.37-15975-238757907776132="` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool.py
<localhost> PUT /home/rkanagas/.ansible/tmp/ansible-local-15868SEr1__/tmpjFf9B7 TO /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132/AnsiballZ_bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132/ /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132/AnsiballZ_bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132/AnsiballZ_bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/rkanagas/.ansible/tmp/ansible-tmp-1613165488.37-15975-238757907776132/ > /dev/null 2>&1 && sleep 0'
changed: [bigip] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "aggregate": null, 
            "description": null, 
            "lb_method": "ratio-member", 
            "metadata": null, 
            "monitor_type": null, 
            "monitors": [
                "http"
            ], 
            "name": "web", 
            "partition": "Common", 
            "priority_group_activation": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.10.1", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "replace_all_with": false, 
            "reselect_tries": null, 
            "service_down_action": null, 
            "slow_ramp_time": 120, 
            "state": "present"
        }
    }, 
    "lb_method": "ratio-member", 
    "monitor_type": "and_list", 
    "monitors": [
        "/Common/http"
    ], 
    "name": "web", 
    "partition": "Common", 
    "priority_group_activation": 0, 
    "slow_ramp_time": 120
}

TASK [Add members to pool] **********************************************************************************************************************************
task path: /home/rkanagas/stash/automation/ansible/F5/playbook.yaml:24
<localhost> Using network group action bigip for bigip_pool_member
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rkanagas
<localhost> EXEC /bin/sh -c 'echo ~rkanagas && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rkanagas/.ansible/tmp `"&& mkdir "` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253 `" && echo ansible-tmp-1613165490.5-16002-74676367759253="` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<localhost> PUT /home/rkanagas/.ansible/tmp/ansible-local-15868SEr1__/tmpVjjPjA TO /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253/AnsiballZ_bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253/ /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253/AnsiballZ_bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253/AnsiballZ_bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/rkanagas/.ansible/tmp/ansible-tmp-1613165490.5-16002-74676367759253/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_pool_member_payload_AQnlpM/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1651, in main
  File "/tmp/ansible_bigip_pool_member_payload_AQnlpM/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1086, in exec_module
  File "/tmp/ansible_bigip_pool_member_payload_AQnlpM/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1166, in execute
  File "/tmp/ansible_bigip_pool_member_payload_AQnlpM/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1178, in present
  File "/tmp/ansible_bigip_pool_member_payload_AQnlpM/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1254, in exists
failed: [bigip] (item={u'host': u'10.10.10.10', u'name': u'web01'}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": "10.10.10.10", 
            "aggregate": null, 
            "availability_requirements": null, 
            "connection_limit": null, 
            "description": "webserver web01", 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "host": "10.10.10.10", 
            "ip_encapsulation": null, 
            "monitors": null, 
            "name": "web01", 
            "partition": "Common", 
            "pool": "web", 
            "port": 80, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.10.1", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "replace_all_with": false, 
            "reuse_nodes": true, 
            "state": "present"
        }
    }, 
    "item": {
        "host": "10.10.10.10", 
        "name": "web01"
    }, 
    "msg": "The specified pool does not exist"
}
<localhost> Using network group action bigip for bigip_pool_member
<localhost> connection transport is rest
<localhost> EXEC /bin/sh -c 'echo ~rkanagas && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rkanagas/.ansible/tmp `"&& mkdir "` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092 `" && echo ansible-tmp-1613165492.56-16002-96888738523092="` echo /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<localhost> PUT /home/rkanagas/.ansible/tmp/ansible-local-15868SEr1__/tmpIL8xLx TO /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092/AnsiballZ_bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092/ /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092/AnsiballZ_bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092/AnsiballZ_bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/rkanagas/.ansible/tmp/ansible-tmp-1613165492.56-16002-96888738523092/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_pool_member_payload_8antjT/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1651, in main
  File "/tmp/ansible_bigip_pool_member_payload_8antjT/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1086, in exec_module
  File "/tmp/ansible_bigip_pool_member_payload_8antjT/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1166, in execute
  File "/tmp/ansible_bigip_pool_member_payload_8antjT/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1178, in present
  File "/tmp/ansible_bigip_pool_member_payload_8antjT/ansible_bigip_pool_member_payload.zip/ansible/modules/network/f5/bigip_pool_member.py", line 1254, in exists
failed: [bigip] (item={u'host': u'10.10.10.20', u'name': u'web02'}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": "10.10.10.20", 
            "aggregate": null, 
            "availability_requirements": null, 
            "connection_limit": null, 
            "description": "webserver web02", 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "host": "10.10.10.20", 
            "ip_encapsulation": null, 
            "monitors": null, 
            "name": "web02", 
            "partition": "Common", 
            "pool": "web", 
            "port": 80, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.10.1", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "replace_all_with": false, 
            "reuse_nodes": true, 
            "state": "present"
        }
    }, 
    "item": {
        "host": "10.10.10.20", 
        "name": "web02"
    }, 
    "msg": "The specified pool does not exist"
}

PLAY RECAP **************************************************************************************************************************************************
bigip                      : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

**Comment by trinaths** [comment] 2021-02-16 14:24
Created INFRAANO-203 for PM tracking

**Comment by ramganesh19** [comment] 2021-02-20 17:48
Hi @trinaths Can you please let me know which older version it works, so that I can continue making progress

**Comment by nmenant** [comment] 2021-03-04 09:40
Hi,

BIG-IP v14.1.2.7

i've tested with the following: 

``` (Ansible) PAR-ML-00026375:test_pool_member menant$ ansible-galaxy collection list

# /Users/menant/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     1.0.0
f5networks.f5_bigip   1.0.0
f5networks.f5_modules 1.8.0
(Ansible) PAR-ML-00026375:test_pool_member menant$
``` 

my playbook: 

``` 
---

- hosts: default
  gather_facts: false
  vars: 
    provider:
      server: 192.168.143.154
      user: admin
      password: xxxxxxxxxx
      validate_certs: no
      server_port: 443

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
        monitors: http
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      loop:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02
      delegate_to: localhost    

``` 

and it works as expected: 

``` 
(Ansible) PAR-ML-00026375:test_pool_member menant$ ansible-playbook -i hosts site.yml

PLAY [default] ***************************************************************************************************************************************************************************************************************

TASK [show sys version] ******************************************************************************************************************************************************************************************************
ok: [192.168.143.154]

PLAY RECAP *******************************************************************************************************************************************************************************************************************
192.168.143.154            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

(Ansible) PAR-ML-00026375:test_pool_member menant$ ansible-playbook -i hosts site.yml

PLAY [default] ***************************************************************************************************************************************************************************************************************

TASK [Create a pool] *********************************************************************************************************************************************************************************************************
changed: [192.168.143.154]

TASK [Add members to pool] ***************************************************************************************************************************************************************************************************
changed: [192.168.143.154] => (item={'host': '10.10.10.10', 'name': 'web01'})
changed: [192.168.143.154] => (item={'host': '10.10.10.20', 'name': 'web02'})

PLAY RECAP *******************************************************************************************************************************************************************************************************************
192.168.143.154            : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

``` 

![image](https://user-images.githubusercontent.com/13098758/109943834-e235ff80-7cd5-11eb-8eef-b33139cadeb8.png)

**Comment by trinaths** [comment] 2021-03-16 14:37
unable to reproduce the issue. closing the issue.

**Closed by trinaths** 2021-03-16 14:37 UTC
Labels: backlog, bug
