### ISSUE TITLE
Bigip_static_route module does not raise an error even if the API endpoint returns a 401 error response

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-ansible#2088] opened 2021-08-11 04:23 UTC
##### COMPONENT NAME

bigip_static_route

##### ANSIBLE VERSION

```
2.9.17
```
##### BIGIP VERSION

```
BIG-IP v15.1.2.1 
```
##### OS / ENVIRONMENT
Ubuntu (Linux)

##### SUMMARY
For an admin user or any other role that is authorized to create a default gateway/static route, the REST API (appcenter/F5Networks/F5ACIServiceCenter/createbigiproutes.json) returns a 200 success response code and the static route is created successfully on the BIG-IP, whereas for a Guest user Authentication the REST API for creating a static route raises a 401 error response and static route is not created. However if the static route is created using Bigip_static_route ansible module with Guest user credentials and same configuration, it does not raise an error and the output log for this execution displays ok=1, failed=0. 
As the REST API fails to create the static route and returns a 401 error response, the ansible module should also raise an error and display ok = 0, failed=1 in the output log

##### STEPS TO REPRODUCE

```
- name: Create/destroy Static Route
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create static route
      bigip_static_route:
        provider:
            server: "{{ url }}"
            server_port: "{{ port }}"
            user: "{{ guest_username }}"
            password: "{{ guest_password }}"
            validate_certs: no
            timeout: 60
        partition: "{{ partition }}"
        name: "{{ name }}"
        destination: "{{ destination }}"
        netmask: "{{ netmask }}"
        gateway_address: "{{ gateway }}"
        state: "{{ state }}"


```

##### EXPECTED RESULTS
The static route created using Bigip_static_route ansible module with Guest user credentials should also raise a 401 error and display ok = 0, failed=1 in the output log as the REST API fails to create the static route and returns a 401 error response

{"code":401,"message":"Authorization failed: user=’some url here’ verb=POST,"restOperationId":99307,"kind":":resterrorresponse"}

##### ACTUAL RESULTS

```
PLAY [Create/destroy Static Route] **************************************************************

TASK [Create static route on BIG-IP] ***********************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

**Comment by trinaths** [comment] 2021-08-18 12:53
@selinaarokiaswamy-GSLAB - unable to reproduce this issue. Can you share more info or re-verify this issue ?

**Comment by selinaarokiaswamy-GSLAB** [comment] 2021-08-19 05:56
> @selinaarokiaswamy-GSLAB - unable to reproduce this issue. Can you share more info or re-verify this issue ?

Hi. You would have to provide credentials for guest user login for this issue to reproduce.

**Comment by trinaths** [comment] 2021-09-13 15:27
@selinaarokiaswamy-GSLAB - Does this worked in the past releases ? if not file a RFE rather than a bug.

**Comment by selinaarokiaswamy-GSLAB** [comment] 2021-11-09 09:11
> @selinaarokiaswamy-GSLAB - Does this worked in the past releases ? if not file a RFE rather than a bug.

Hi @trinaths I think that this is more of a bug rather than a RFE as the Bigip_static_route ansible module is not raising the correct error for the REST API call when the REST API returns the correct error response if static route is created using a Guest login. I have updated the above issue to add more details regarding this behavior. Kindly have a look and let me know in case of queries. Thanks

**Comment by wojtek0806** [comment] 2021-11-09 09:34
Yes it is a bug, in either of the places:

https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_static_route.py#L585
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_static_route.py#L624

Some modules on_device methods have not been updated with better patterns to detect scenarios like this, @trinaths  please log this internally, we might have to do similar updates to other modules in collection

**Comment by KrithikaChidambaram** [comment] 2023-02-17 09:11
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!

**Closed by KrithikaChidambaram** 2023-02-17 09:11 UTC
Labels: bug, awaiting-user-action
