### ISSUE TITLE
Random exceptions for set_session_enabled_state

### ISSUE THREAD

**Issue by hanej** [F5Networks/f5-ansible#50] opened 2016-11-09 16:01 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_node

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       0.0.401
  Edition     Final
  Date        Mon Aug 11 21:08:03 PDT 2014
```

##### OS / ENVIRONMENT

Red Hat 7.2

##### SUMMARY

Occasionally when trying to enable or disable a node the bigip_node module will produce an exception and the entire playbook stops.

##### STEPS TO REPRODUCE

```
    - name: disable node on primary F5
      bigip_node: server='192.168.x.x'
                  user='ansible'
                  password='password'
                  name='test_node'
                  session_state=disabled
                  monitor_state=disabled
                  validate_certs=False
      register: f5_result
```

##### EXPECTED RESULTS

The node is disabled and any exceptions are handled within the module.  The register variable should hold any errors trying to modify the node.

##### ACTUAL RESULTS

This doesn't happen all the time and it's hard to reproduce.  I would like to be able to trap these errors and handle them gracefully in the playbook.

```
fatal: [app1 -> jumpserver]: FAILED! => {"changed": false, "failed": true, "msg": "received exception: Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/NodeAddressV2::set_session_enabled_state()\nException: Common::OperationFailed\n\tprimary_error_code   : 17241203 (0x01071473)\n\tsecondary_error_code : 0\n\terror_string         : 01071473:3: Create, modify, and delete commands are not valid for (by class: node_address) while in the root folder.'"}
```

**Comment by caphrim007** [comment] 2016-11-09 16:23
This is a catchable exception, so i will try to do so in the code.

The longer term fix is to abandon the soap api because of its insistence on doing the moral equivalent of

`cd partition`

This is addressed in 5he rest api as simply being a property of the resource

**Comment by hanej** [comment] 2016-11-09 16:45
Thank you.  If you have a good module to model after, I can help with things like this.  We have a huge and pressing need to automate a lot of our F5 work and we'll need this sooner rather than later.

**Comment by caphrim007** [comment] 2016-11-09 18:15
@hanej I would appreciate your testing of the updated code in your real-world environment, bug reporting, and feature requests above and beyond code contributions.

Just to be clear though, let me preface the above statement with "at this time".

The code is not the most difficult effort for the module development. Much harder for me is to run the modules in an environment that has had BIG-IP taken through hell and back.

I work off of pristine VE images, so I have a skewed view of the world. But since yourself and this audience uses these in production, your experiences with it would be infinitely more helpful to have.

I will update you when I have pushed an updated copy of the `bigip_node` module that uses the REST api.

**Comment by hanej** [comment] 2016-11-09 18:17
No problem.  Thanks

**Comment by hanej** [comment] 2016-11-09 20:08
Actually we did a deployment today and we hit that error every single time only on one pair of F5s.  The other pair had no issue.  We cannot get it to work at all so if there is anything you want me to test I can do so.

**Comment by mleklund** [comment] 2017-02-22 18:59
this is happening to me as well.

**Comment by jkkarant89** [comment] 2017-03-31 05:24
This problem has been noticed even when performing enable/disable of a GTM WideIP.
To trace this down the problem seems to be intermittent.

Was there any solution to the problem apart from moving to REST identified? (migrating to REST not possible as not all versions of F5 are REST enabled).

**Comment by caphrim007** [comment] 2017-03-31 05:57
@jkkarant89 i do not have a reliable repro from which to test. I can provide a debug version of the module for anyone interested in running it in production and attempting to catch the cause of the exception.

**Comment by hanej** [comment] 2017-03-31 11:14
I had to move this functionality to a Python script that is called from Ansible.  Haven't had the problem since.

**Comment by perzizzle** [comment] 2017-06-02 19:57
@caphrim007 I encounter this exception every so often. Are you still looking for people to test out a newer version of this module? Looks like the version in this repo compared to what ships with ansible 2.3 is very different.

**Comment by caphrim007** [comment] 2017-09-29 22:44
@perzizzle @hanej @jkkarant89 @mleklund bigip_node (in this repo) has been refactored. please download it and raise any issues you may encounter.

**Closed by caphrim007** 2017-09-29 22:44 UTC
Labels: bug-report
