### ISSUE TITLE
bigip_command does not utilize F5_Server environment variable when transport=CLI

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1202] opened 2019-02-04 17:20 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4

##### SUMMARY

When calling bigip_command using transport=CLI, the value of the F5_Server environment variable value is ignored, and an error will occur unless the server parameter is specified.  With no other change except changing to transport=REST, the playbook runs correctly.  The playbook with success using REST and failure using CLI is attached.

##### STEPS TO REPRODUCE

```
See Test.yaml in gist:
https://gist.github.com/C0missar/a1f2b4398341acecbed1b9a954aa24b8
```

##### EXPECTED RESULTS

I expected that the results of all three tasks would be identical - REST using F5_SERVER environment variable, CLI using server parameter, and CLI using F5_SERVER environment variable.

##### ACTUAL RESULTS

The third task, CLI using F5_SERVER environment variable, failed with "AnsibleConnectionFailure: 'NoneType' object has no attribute 'lower'"

```
See Test.log in gist:
https://gist.github.com/C0missar/a1f2b4398341acecbed1b9a954aa24b8
```

**Comment by wojtek0806** [comment] 2019-02-04 17:31
@C0missar thanks for that, can you repaste gist link to YAML, looks like the link to log was pasted twice :)

**Comment by C0missar** [comment] 2019-02-04 17:38
Both files (Test.yaml and Test.log) are in the same gist.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by C0missar** [comment] 2019-02-05 23:03
It appears that F5_USER is not honored, either, and this is also only when using transport CLI.

**Comment by wojtek0806** [comment] 2019-03-27 18:46
The issue is with this line of code:

https://github.com/F5Networks/f5-ansible/blob/devel/library/plugins/action/bigip.py#L72

When SERVER is not specified, the provider still has the 'server' key so this method returns None rather than the content of: self._play_context.remote_addr.

Few other things to note for my own benefit and yours :) :

- When you specify ENV variables in your bash profile:
```
F5_SERVER
F5_USER
```
and also specify them in the playbook:

```
  environment:
      F5_SERVER:                        <stripped>
      F5_USER:                          <stripped>
```

The bash profile specified variables will trump the ones from the playbook.

**Some context**: 

During execution process the action plugin bigip.py, used for transport: cli connections will do the following:

- When module is launched, the f5_provider_spec is populated where the env_fallback uses **system local variables**

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_command.py#L707

- Next the plugin will use the f5_provider_spec and task arguments, and parse them with load_provider function, the task arguments will contain all arguments passed to the module, since we already parsed the argument spec once at module initialisation, the provider will be there but with the env variables values from the system

https://github.com/F5Networks/f5-ansible/blob/devel/library/module_utils/network/f5/common.py#L29
https://github.com/F5Networks/f5-ansible/blob/devel/library/plugins/action/bigip.py#L63

- Next the connection plugin will set the connection parameters to pass along to other connection plugins used by ansible to setup SSH connection, at this stage we involve: `self._play_context` which is where your ENVIRONMENT variables from the playbook come in.

https://github.com/F5Networks/f5-ansible/blob/devel/library/plugins/action/bigip.py#L72

The fix for this issue is to change the following assignments:
```
     pc.remote_addr = provider.get('server', self._play_context.remote_addr)
     pc.port = int(provider['server_port'] or self._play_context.port or 22)
     pc.remote_user = provider.get('user', self._play_context.connection_user)
     pc.password = provider.get('password', self._play_context.password)
```

**Comment by wojtek0806** [comment] 2019-03-27 18:52
actually it would be easier to remove (key: None) values from provider

**Comment by wojtek0806** [comment] 2019-03-27 19:13
The change:

```
                pc.remote_addr = provider['server'] or self._play_context.remote_addr
                pc.remote_user = provider['user'], self._play_context.connection_user
                pc.password = provider['password'], self._play_context.password
```

**Closed** 2019-03-27 19:30 UTC
Labels: bug-report, fails-on-devel

**Comment by C0missar** [comment] 2019-03-28 01:33
The issue with that is that we use both transports in the same playbook, in order to set the admin password, since that function is broken in the supported CFT.


Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com

http://www.sherwin-williams.com



-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>
