### ISSUE TITLE
bigip_firewall_address_list - unable to create "address_list"

### ISSUE THREAD

**Issue by mkyrc** [F5Networks/f5-ansible#1887] opened 2020-10-19 23:46 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_firewall_address_list

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/horol/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/horol/VIRTUALENV/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/horol/VIRTUALENV/ansible/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### PYTHON VERSION

```
Python 3.8.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.5
  Build       0.0.8
  Edition     Point Release 5
  Date        Mon Aug 24 01:16:01 PDT 2020
```

##### CONFIGURATION

```
  tasks:
    - name: Create an address list
      bigip_firewall_address_list:
        provider: "{{ provider }}"
        name: "tmpname"
        addresses:
          - 3.3.3.1
          - 4.4.4.4
          - 5.5.5.5
      delegate_to: localhost
```

##### OS / ENVIRONMENT

```
Ubuntu 20.04.1 LTS
```

##### SUMMARY

Unable to create (simple) AFM "address list". The same issue is connected with "address ranges".

##### STEPS TO REPRODUCE

"fw-t-egov.yaml" file:
```
---
- name: AFM objects 
  hosts: bigip_aci_01
  connection: local
  vars_files: 
    - ../../01-configs/00-vars-provider.yaml

  tasks:
    - name: Create an address list
      f5networks.f5_modules.bigip_firewall_address_list:
        provider: "{{ provider }}"
        name: "tmpname"
        addresses:
          - 3.3.3.1
          - 4.4.4.4
          - 5.5.5.5
      delegate_to: localhost
```

##### EXPECTED RESULTS

AFM address list creation.

##### ACTUAL RESULTS

$ ansible-playbook fw-t-egov.yaml -i ../../00-inventory/hosts -C -vvvv
```
ansible-playbook 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/horol/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/horol/VIRTUALENV/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/horol/VIRTUALENV/ansible/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/horol/DEV/mvpilot/04-ansible/00-inventory/hosts as it did not pass its verify_file() method
script declined parsing /home/horol/DEV/mvpilot/04-ansible/00-inventory/hosts as it did not pass its verify_file() method
auto declined parsing /home/horol/DEV/mvpilot/04-ansible/00-inventory/hosts as it did not pass its verify_file() method
Parsed /home/horol/DEV/mvpilot/04-ansible/00-inventory/hosts inventory source with ini plugin
Loading collection f5networks.f5_modules from /home/horol/.ansible/collections/ansible_collections/f5networks/f5_modules
Loading callback plugin default of type stdout, v2.0 from /home/horol/VIRTUALENV/ansible/lib/python3.8/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: fw-t-egov.yaml **********************************************************************************************************************************************************
Positional arguments: fw-t-egov.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
check: True
inventory: ('/home/horol/DEV/mvpilot/04-ansible/00-inventory/hosts',)
forks: 5
1 plays in fw-t-egov.yaml
Read vars_file '../../01-configs/00-vars-provider.yaml'
Read vars_file '../../01-configs/00-vars-provider.yaml'
Read vars_file '../../01-configs/00-vars-provider.yaml'

PLAY [firewall "t-egov"] **********************************************************************************************************************************************************
Read vars_file '../../01-configs/00-vars-provider.yaml'

TASK [Gathering Facts] ************************************************************************************************************************************************************
task path: /home/horol/DEV/mvpilot/04-ansible/03-playbooks/01-t-egov/fw-t-egov.yaml:5
<bigip_aci_01> ESTABLISH LOCAL CONNECTION FOR USER: horol
<bigip_aci_01> EXEC /bin/sh -c 'echo ~horol && sleep 0'
<bigip_aci_01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/horol/.ansible/tmp `"&& mkdir "` echo /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787 `" && echo ansible-tmp-1603150853.7191424-4207-108873340401787="` echo /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787 `" ) && sleep 0'
<bigip_aci_01> Attempting python interpreter discovery
<bigip_aci_01> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<bigip_aci_01> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /home/horol/VIRTUALENV/ansible/lib/python3.8/site-packages/ansible/modules/setup.py
<bigip_aci_01> PUT /home/horol/.ansible/tmp/ansible-local-4203ii0ls7uz/tmpveli9acf TO /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787/AnsiballZ_setup.py
<bigip_aci_01> EXEC /bin/sh -c 'chmod u+x /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787/ /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787/AnsiballZ_setup.py && sleep 0'
<bigip_aci_01> EXEC /bin/sh -c '/usr/bin/python3 /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787/AnsiballZ_setup.py && sleep 0'
<bigip_aci_01> EXEC /bin/sh -c 'rm -f -r /home/horol/.ansible/tmp/ansible-tmp-1603150853.7191424-4207-108873340401787/ > /dev/null 2>&1 && sleep 0'
ok: [bigip_aci_01]
Read vars_file '../../01-configs/00-vars-provider.yaml'
META: ran handlers
Read vars_file '../../01-configs/00-vars-provider.yaml'
Read vars_file '../../01-configs/00-vars-provider.yaml'

TASK [Create an address list] *****************************************************************************************************************************************************
task path: /home/horol/DEV/mvpilot/04-ansible/03-playbooks/01-t-egov/fw-t-egov.yaml:14
Loading collection ansible.netcommon from /home/horol/.ansible/collections/ansible_collections/ansible/netcommon
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: horol
<localhost> EXEC /bin/sh -c 'echo ~horol && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/horol/.ansible/tmp `"&& mkdir "` echo /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607 `" && echo ansible-tmp-1603150855.2256534-4287-239829009616607="` echo /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607 `" ) && sleep 0'
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
Using module file /home/horol/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py
<localhost> PUT /home/horol/.ansible/tmp/ansible-local-4203ii0ls7uz/tmpflr2umw1 TO /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/ /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/horol/VIRTUALENV/ansible/bin/python /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py", line 102, in <module>
    _ansiballz_main()
  File "/home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_firewall_address_list', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 989, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 982, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 787, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 608, in to_return
  File "/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 619, in addresses
TypeError: 'NoneType' object is not iterable
fatal: [bigip_aci_01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/horol/.ansible/tmp/ansible-tmp-1603150855.2256534-4287-239829009616607/AnsiballZ_bigip_firewall_address_list.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_firewall_address_list', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 989, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 982, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 787, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 608, in to_return\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload_lf8m14ka/ansible_f5networks.f5_modules.bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 619, in addresses\nTypeError: 'NoneType' object is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
syslog:
```
Oct 20 01:40:54 localhost python3[4234]: ansible-ansible.legacy.setup Invoked with gather_subset=['all'] gather_timeout=10 filter=* fact_path=/etc/ansible/facts.d
Oct 20 01:40:55 localhost ansible-f5networks.f5_modules.bigip_firewall_address_list: Invoked with provider={'user': 'api', 'password': '********', 'server': '172.25.246.27', 'validate_certs': False, 'server_port': 443, 'transport': 'rest', 'timeout': None, 'no_f5_teem': None, 'auth_provider': None} name=tmpname addresses=['3.3.3.1', '4.4.4.4', '5.5.5.5'] partition=Common state=present description=None address_ranges=None address_lists=None geo_locations=None fqdns=None
```

**Comment by horol** [comment] 2020-10-20 19:42
### UPDATE:
The issue is connected to ansible version 2.10.x (2.10.0, 2.10.1, 2.10.2) - there are lot of f5 network modules that aren't working. For example module "bigip_command" is working with ansible 2.10.x, but "bigip_firewall_address_list" ends with traceback.

**Everything is working correctly with Ansible version 2.9** (F5 Modules Collection version 1.6.0, python 3.8.5).

Based on f5 modules for Ansible release note (https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/supported-versions.html), there is matrix of supported BIG-IP and Ansible versions:

- **BIG-IP 15.x** is missing - is 1.6.0 collection supported for 15.x version? 
- Also **Ansible 2.10** is missing from matrix - the question is, if this latest ansible version is supported (in the future) or no road map for supporting 2.10.x exists.

Does anyone know the answer to these questions?

Thanks,
Martin

**Comment by KrithikaChidambaram** [comment] 2022-12-08 18:43
Closing this now. Reopen if you still face the issue. Thanks!

**Closed by KrithikaChidambaram** 2022-12-08 18:43 UTC
