### ISSUE TITLE
BUG: bigip_profile_http, header_insert parameter can not accept: "nsclientip:[IP::remote_addr]"

### ISSUE THREAD

**Issue by jewettg** [F5Networks/f5-ansible#1907] opened 2020-11-05 23:32 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_profile_http

##### ANSIBLE VERSION
```
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jewettg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.13/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### PYTHON VERSION
```
Python 2.7.16
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.5
  Build       0.0.3
  Edition     Point Release 5
  Date        Sat May  9 09:31:20 PDT 2020
```

##### CONFIGURATION
FROM:  /etc/ansible/ansible.cfg
# Paths to search for collections, colon separated
collections_paths = ~/.ansible/collections:/etc/ansible/collections
OLDPWD=/Users/jewettg/.ansible
PWD=/Users/jewettg/ansible
ANSIBLE_CONFIG=/etc/ansible/ansible.cfg

##### OS / ENVIRONMENT
Mac OS 10.15.7 (19H2)

##### SUMMARY
Attempting to use insert the following header "nsclientip:[IP::remote_addr]" using the "header_insert" parameter of "bigip_profile_http".  I receive the following error: Invalid header format: nsclientip:[IP::remote_addr]
The parameter works if I remove the "::" part, which I believe is the parsing error bug.
https://clouddocs.f5.com/api/irules/IP__remote_addr.html

##### STEPS TO REPRODUCE
attempt to use the following code in a playbook.  

```
---
    -   name: Create a VIP, pool and pool members
        hosts: test_c1a
        connection: local

        collections:
            - f5networks.f5_module
              
        tasks:
        -   name: "CREATE: service http profile profile std_https_prof"
            bigip_profile_http:
                name: std_https_prof
                insert_xforwarded_for: yes
                redirect_rewrite: all
                # header_insert: "nsclientip:[IP::remote_addr]"
                state: present
                parent: http
                enforcement:
                    unknown_method: allow
                provider: "{{ test_f5_c1a }}"
```

##### EXPECTED RESULTS
Update the F5 profile field with the "header" string provided.   

##### ACTUAL RESULTS

```
ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jewettg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.13/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /Users/jewettg/ansible/hosts as it did not pass its verify_file() method
script declined parsing /Users/jewettg/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /Users/jewettg/ansible/hosts as it did not pass its verify_file() method
Parsed /Users/jewettg/ansible/hosts inventory source with ini plugin

PLAYBOOK: test.yml *******************************************************************************************************************************************************************
1 plays in ./test.yml

PLAY [Create a VIP, pool and pool members] *******************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
task path: /Users/jewettg/ansible/test.yml:2
<f5-c1a-t1.its.utexas.edu> ESTABLISH LOCAL CONNECTION FOR USER: jewettg
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'echo ~jewettg && sleep 0'
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jewettg/.ansible/tmp `"&& mkdir "` echo /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140 `" && echo ansible-tmp-1604619091.687389-24837-218830639854140="` echo /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140 `" ) && sleep 0'
<f5-c1a-t1.its.utexas.edu> Attempting python interpreter discovery
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<f5-c1a-t1.its.utexas.edu> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /usr/local/Cellar/ansible/2.9.13/libexec/lib/python3.8/site-packages/ansible/modules/system/setup.py
<f5-c1a-t1.its.utexas.edu> PUT /Users/jewettg/.ansible/tmp/ansible-local-24833qn0gr4ty/tmpdouqqlsv TO /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140/AnsiballZ_setup.py
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'chmod u+x /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140/ /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140/AnsiballZ_setup.py && sleep 0'
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c '/usr/bin/python /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140/AnsiballZ_setup.py && sleep 0'
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'rm -f -r /Users/jewettg/.ansible/tmp/ansible-tmp-1604619091.687389-24837-218830639854140/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Platform darwin on host f5-c1a-t1.its.utexas.edu is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter
could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [f5-c1a-t1.its.utexas.edu]
META: ran handlers

TASK [CREATE: service http profile profile std_https_prof] ***************************************************************************************************************************
task path: /Users/jewettg/ansible/test.yml:10
<f5-c1a-t1.its.utexas.edu> ESTABLISH LOCAL CONNECTION FOR USER: jewettg
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'echo ~jewettg && sleep 0'
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jewettg/.ansible/tmp `"&& mkdir "` echo /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880 `" && echo ansible-tmp-1604619092.704268-24874-41494036351880="` echo /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880 `" ) && sleep 0'
Using module file /usr/local/Cellar/ansible/2.9.13/libexec/lib/python3.8/site-packages/ansible/modules/network/f5/bigip_profile_http.py
<f5-c1a-t1.its.utexas.edu> PUT /Users/jewettg/.ansible/tmp/ansible-local-24833qn0gr4ty/tmp6ywhz_gg TO /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880/AnsiballZ_bigip_profile_http.py
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'chmod u+x /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880/ /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880/AnsiballZ_bigip_profile_http.py && sleep 0'
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c '/usr/bin/python /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880/AnsiballZ_bigip_profile_http.py && sleep 0'
<f5-c1a-t1.its.utexas.edu> EXEC /bin/sh -c 'rm -f -r /Users/jewettg/.ansible/tmp/ansible-tmp-1604619092.704268-24874-41494036351880/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1750, in main
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1515, in exec_module
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1535, in present
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1546, in update
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1504, in should_update
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1490, in _update_changed_options
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1367, in compare
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1416, in header_insert
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 994, in header_insert
  File "/var/folders/7l/c1w_gq0n1jjbx67n6bh0gjmc0000gn/T/ansible_bigip_profile_http_payload_1OCZdP/ansible_bigip_profile_http_payload.zip/ansible/module_utils/network/f5/urls.py", line 34, in check_header_validity
    raise F5ModuleError('Invalid header format: {0}'.format(header))
[WARNING]: Module did not set no_log for update_password
fatal: [f5-c1a-t1.its.utexas.edu]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_xff": null,
            "description": null,
            "dns_resolver": null,
            "encrypt_cookie_secret": null,
            "encrypt_cookies": null,
            "enforcement": {
                "excess_client_headers": null,
                "excess_server_headers": null,
                "known_methods": null,
                "max_header_count": null,
                "max_header_size": null,
                "max_requests": null,
                "oversize_client_headers": null,
                "oversize_server_headers": null,
                "pipeline": null,
                "truncated_redirects": null,
                "unknown_method": "allow"
            },
            "fallback_host": null,
            "fallback_status_codes": null,
            "header_erase": null,
            "header_insert": "nsclientip:[IP::remote_addr]",
            "hsts_mode": null,
            "include_subdomains": null,
            "insert_xforwarded_for": true,
            "maximum_age": null,
            "name": "std_https_prof",
            "oneconnect_transformations": null,
            "parent": "http",
            "partition": "Common",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "f5-c1a-t1.its.utexas.edu",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "fc5774",
                "validate_certs": false
            },
            "proxy_type": null,
            "redirect_rewrite": "all",
            "request_chunking": null,
            "response_chunking": null,
            "server_agent_name": null,
            "sflow": null,
            "state": "present",
            "update_password": "always",
            "xff_alternative_names": null
        }
    }
}

MSG:

Invalid header format: nsclientip:[IP::remote_addr]

PLAY RECAP ***************************************************************************************************************************************************************************
f5-c1a-t1.its.utexas.edu   : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by Learloj** [comment] 2020-11-10 13:21
Hi @jewettg!

I ran into this because of the same cause but different problem. Based on your description, I think you are trying to set the 'nsclientip' header to the IP address of the remote (client). The '[IP::remote_addr]' which you also link to is, as far as I know, only limited to iRules. So you can either use an iRule to set this header, or you use the existing X-Forwarded-For header (which you already enabled).

An iRule could look something like this (not tested) and could be uploaded via bigip_irule:
```
when HTTP_REQUEST {
  HTTP::header replace nsclientip [IP::client_addr]
}
```

**Comment by Learloj** [comment] 2020-11-10 13:35
FYI, I described my issue and where I found to be the cause in #1910, which comes down to bigip_profile_http's header_insert not accepting more than one colon (:) character.

**Comment by jewettg** [comment] 2020-11-10 20:06
@Learloj -- Thank you so much for the response, however this is not for a programmatic approach, but one via Ansible and YAML playbooks.  I do not have the capability to insert python code in the YAML file.

Currently the "[IP::client_addr]" is not limited to just iRules, as this profile configuration works as configured in the GUI and via TMSH commands.

**GUI:** ![test_http_prof_GUI](https://user-images.githubusercontent.com/17208818/98727380-6e09d180-235d-11eb-8d99-29c18afa5526.png)

**TMSH:**  create ltm profile http "test_http_prof" defaults-from http insert-xforwarded-for enabled header-insert "nsclientip:[IP::remote_addr]" enforcement { unknown-method allow }

I was hoping to replicate the configuration in an Ansible playbook so I can create Ansible playbook versions of my services that we can check into RH Ansible Tower and GitHub.   

Are you aware of any methods of escaping out the colons to have the parser ignore them?  Can you think of any other way to provide a literal string that does not require escaping or parsing of the string?

_If not, I believe that this is most definitely a bug! :-(_

**Comment by jewettg** [comment] 2020-11-10 20:10
@Learloj  - Explanation, this header is being put into place with basically the same data as the "X-Forwarded-For" for two main reason, one to double-check the value of "X-Forward-For" (since it can be intercepted and changed) and for compatibility reasons with a service that requires the SourceIP to show up in a different header and will not retrieve the value from "X-Forwarded-For" header.  

So I am stuck.  I need to be able to set this header in an Ansible playbook.  Any ideas?

**Comment by Learloj** [comment] 2020-11-11 07:03
@jewettg does that GUI config actually work? If so, then I didn't know you could use TCL code in those fields too :-D

That said, I think it is definitely a bug, as I described in #1910 where I also supplied a fix, but this would have to be fixed in the Ansible module for F5.

In the mean time you could implement a workaround by creating an iRule via the Ansible 'bigip_irule' module like I described in [my earlier comment](https://github.com/F5Networks/f5-ansible/issues/1907#issuecomment-724697691) and then attach that iRule to the VirtualServer you are configuring via the Ansible F5 module bigip_virtual_server using the 'irules' parameter. Not the nicest way, but I believe it should work.

**Comment by focrensh** [comment] 2020-11-11 15:55
Thank you for reporting, closing this into #1910

**Closed by focrensh** 2020-11-11 15:55 UTC

**Comment by jewettg** [comment] 2020-11-13 21:57
@learloj -->  Yes, this configuration works using the GUI and TMSH, and we have been using it for years through multiple versions of TMOS.  Thanks for filing the bug report, I hope it gets fixed soon!
