### ISSUE TITLE
bigip_vlan tagged_interface

### ISSUE THREAD

**Issue by mikeandretta** [F5Networks/f5-ansible#304] opened 2017-08-09 20:07 UTC
Im looking to use tagged_interface: "Virtuals" as my tagged interface for the newly created bigip_vlan. If I already have a trunk with interface 1.1 and 1.2 inside of it and I want to use the trunked "string" value within the tagged_interface: why is this not an option? Below is my YML for this section. All works for VLAN creation but it will not tag the Network \ Trunks interface im trying to reference (Virtuals).

Thanks!

Just an FYI, I am using a physical pair, not the VE.

```
    - name: Tag Interface
      bigip_vlan:
          tagged_interface: "{{ taggedinterface }}"
          name: "{{ vlanname }}"
          password: "{{ passwordhere }}"
          server: "{{ inventory_hostname }}"
          tag: "{{ vlantag }}"
          user: "admin"
          validate_certs: "false"
      delegate_to: localhost
```

**Comment by fatred** [comment] 2017-09-06 13:29
I have the same issue: if I refer to a x.x port then it works, but if i refer to a trunk "aci_vpc" then it says it cannot find that interface.

**Comment by caphrim007** [comment] 2017-09-06 21:06
@mikeandretta @fatred this is likely due to trunks not existing on VE's, so we havent tested stuff/designed for stuff like that. But we can indeed add it.

**Comment by fatred** [comment] 2017-09-06 22:19
+1 for the feature request then!

**Comment by mgontarczyk** [comment] 2017-09-11 10:08
I've got the same problem, interface is present, but when adding tag to trunk error is thrown.
`"ansible_facts": {
        "trunk": {
            "Port-channel21": {
                "active_lacp_state": "STATE_ENABLED", 
                "configured_member_count": 2, 
                "description": "", 
                "distribution_hash_option": "DISTRIBUTION_HASH_OPTION_SRC_DST_MAC", 
                "interface": [
                    "1.3", 
                    "1.4"
                ], 
                "lacp_enabled_state": "STATE_ENABLED", 
                "lacp_timeout_option": "LACP_TIMEOUT_LONG", 
                "link_selection_policy": "LINK_SELECTION_AUTO", 
                "media_speed": 2000, 
                "media_status": "MEDIA_STATUS_UP", 
                "operational_member_count": 2, 
                "stp_enabled_state": "STATE_ENABLED", 
                "stp_protocol_detection_reset_state": "STATE_DISABLED"
            }
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "filter": null, 
            "include": [
                "trunk"
            ], 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server": "10.x.x.x", 
            "server_port": 443, 
            "session": false, 
            "state": "present", 
            "user": "mgontarczyk", 
            "validate_certs": false
        }
    }
}`

`"msg": "The specified interface \"Port-channel21\" was not found"}`

**Comment by wojtek0806** [comment] 2017-09-18 20:05
duplicate of #329

**Comment by delgadillo22** [comment] 2018-01-11 18:11
High if VLAN trunks are used ubiquitously. Medium otherwise.

**Closed** 2018-03-27 19:39 UTC
Labels: bug-report, enhancement, high
