### ISSUE TITLE
bigip_pool_member - FQDN Node already exists as Node 

### ISSUE THREAD

**Issue by kswider92** [F5Networks/f5-ansible#2293] opened 2023-01-20 13:34 UTC
##### COMPONENT NAME

bigip_pool_member v 1.22

##### ANSIBLE VERSION

```
2.10.8
```
##### BIGIP VERSION

```
BIG-IP 15.1.6 Build 0.0.8 Final 
```

##### SUMMARY

When trying to add an existing node created in different partition (Common) to the new pool error says that node already exists, which is true, but tried with reuse_nodes set both to yes and no and the result was the same.

##### STEPS TO REPRODUCE

```
- name: Add pool member loop fqdn
  bigip_pool_member:
    pool: "{{ member.pool_name }}"
    fqdn: "{{ item.host_fqdn }}"
    name: "{{ item.host_fqdn }}"
    partition: "{{ member.partition }}"
    port: "{{ item.host_port }}"
    description: "{{ item.member_description | default([]) }}"
    reuse_nodes: "yes"
    provider: "{{ provider }}"
  delegate_to: localhost
  when: item.host_fqdn is defined
  loop: "{{ members_value }}"


  - pool_name: "pool"
    partition: "custom"
    pool_description: "description"
    dest_ip: "10.151.5.203"
    service_port: "8088"
    healthcheck: "/"
    pool_members:
      - host_fqdn: "member1"
        host_port: 8088
      - host_fqdn: "member2"
        host_port: 8088

failed: [localhost] (item={'host_fqdn': 'member1', 'host_port': 8088}) => {"ansible_loop_var": "item", "changed": false, "item": {"host_fqdn": "member1", "host_port": 8088}, "msg": "b'{\"code\":400,\"message\":\"01070734:3: Configuration error: FQDN Node (/custom/member1:member1) already exists as Node (/Common/member1)\",\"errorStack\":[],\"apiError\":3}'"}
```

##### EXPECTED RESULTS

Pool is being created reusing existing node from Common partition.
##### ACTUAL RESULTS

```
failed: [localhost] (item={'host_fqdn': 'member1', 'host_port': 8088}) => {"ansible_loop_var": "item", "changed": false, "item": {"host_fqdn": "member1", "host_port": 8088}, "msg": "b'{\"code\":400,\"message\":\"01070734:3: Configuration error: FQDN Node (/custom/member1:member1) already exists as Node (/Common/member1)\",\"errorStack\":[],\"apiError\":3}'"}
```

**Comment by KrithikaChidambaram** [comment] 2023-02-21 11:08
Hi, thanks for reporting. Internal tracking fir thia request is: INFRAANO-1078, thanks!

**Comment by wojtek0806** [comment] 2023-02-22 17:27
I have tested this with TMSH and GUI and there 2 things you need to be aware as this is working as intended:

- Existing nodes must be on the same partition as the pool member, for your scenario this means you need to change your `partition` parameter to match `Common`.  I have checked REST api  and the pool member from node on Common is created on Common partition, see the below output:

```
{
    "kind": "tm:ltm:pool:members:memberscollectionstate",
    "selfLink": "https://localhost/mgmt/tm/ltm/pool/~foo~test_pool/members?ver=16.1.3.3",
    "items": [
        {
            "kind": "tm:ltm:pool:members:membersstate",
            "name": "_auto_142.251.34.110:80",
            "partition": "Common",
            "fullPath": "/Common/_auto_142.251.34.110:80",
            "generation": 30669,
            "selfLink": "https://localhost/mgmt/tm/ltm/pool/~foo~test_pool/members/~Common~_auto_142.251.34.110:80?ver=16.1.3.3",
            "address": "142.251.34.110",
            "connectionLimit": 0,
            "dynamicRatio": 1,
            "ephemeral": "true",
            "fqdn": {
                "autopopulate": "disabled",
                "tmName": "google.com"
            },
            "inheritProfile": "enabled",
            "logging": "disabled",
            "monitor": "default",
            "priorityGroup": 0,
            "rateLimit": "disabled",
            "ratio": 1,
            "session": "monitor-enabled",
            "state": "up"
        },
        {
            "kind": "tm:ltm:pool:members:membersstate",
            "name": "gman:80",
            "partition": "Common",
            "fullPath": "/Common/gman:80",
            "generation": 30668,
            "selfLink": "https://localhost/mgmt/tm/ltm/pool/~foo~test_pool/members/~Common~gman:80?ver=16.1.3.3",
            "address": "any6",
            "connectionLimit": 0,
            "dynamicRatio": 1,
            "ephemeral": "false",
            "fqdn": {
                "autopopulate": "disabled",
                "tmName": "google.com"
            },
            "inheritProfile": "enabled",
            "logging": "disabled",
            "monitor": "default",
            "priorityGroup": 0,
            "rateLimit": "disabled",
            "ratio": 1,
            "session": "user-enabled",
            "state": "fqdn-up"
        }
    ]
```

- When creating new pool members (with new nodes) these can be on a non-Common partition, in your case it would be `custom` partition, however these nodes could be be reused by a pool member in another partition. So you if you want to have your members on `custom` partition then set `resuse_nodes: no` and specify new fqdn name for members that won't collide with whatever you have on Common partition.

This is working as intended.

**Comment by pgouband** [comment] 2023-04-03 13:23
Closing this now. Thanks!

**Closed by pgouband** 2023-04-03 13:23 UTC
Labels: not-a-bug, awaiting-user-action
