### ISSUE TITLE
bigip_device_facts module fails when GTM is not provisioned

### ISSUE THREAD

**Issue by tizianorosato** [F5Networks/f5-ansible#1102] opened 2018-12-05 11:41 UTC
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

bigip_device_facts

##### ANSIBLE VERSION

```
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/default/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### PYTHON VERSION

```
Python 2.7.5

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20

```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I'm running a simple playbook gathering all the "facts" from latest ansible 2.7 toward a test f5 box
(f5 virtual edition, ver 13.1.1 with LTM and ASM provisioned).
The playbook fails because GTM/LC is not provisioned.
I expected the playbook to be successfull even without this module runing.
Not clear if this is a know limitation or a bug.

##### STEPS TO REPRODUCE

Setup an F5 device without GTM module. 
Run a playbook with the "all" subset, like this:

bigip_device_facts:
      gather_subset:
        - all

```
---
- name: "Facts Ansible 2.7"
  hosts: bigips
  connection: local

  vars:
    validate_certs: no
    server: XXXXXXXXXX
    username: XXXXXXXXXX
    password: XXXXXXXXXX

  tasks:
  - name: Gather all facts
    bigip_device_facts:
      gather_subset:
        - all
        #-asm-policy-stats
        #- system-info
        #- devices
        #- virtual-servers
        #- ltm-pools
        #- nodes
        #- irules
      provider:
        validate_certs: no
        server: XXXXXXXXXX
        user: XXXXXXXXXX
        password: XXXXXXXXXX
        transport: rest
    delegate_to: localhost
    register: all_the_facts

  - name: Print all the F5 facts
    debug:
      var: all_the_facts

```

##### EXPECTED RESULTS

I expect the playbook to be run succesfully even without the GTM provisioned/running on the f5 box.

##### ACTUAL RESULTS

```
ansible-playbook -i hosts f5-fact-v13.yaml

PLAY [Facts Ansible 2.7] ***************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [192.168.240.131]

TASK [Gather all facts] ****************************************************************************************************************
fatal: [192.168.240.131 -> localhost]: FAILED! => {"changed": false, "msg": "One of the following features must be licensed/provisioned for the URI gtm : gtm lc"}
        to retry, use: --limit @/home/default/ansible/asm1/f5-fact-v13.retry

PLAY RECAP *****************************************************************************************************************************
192.168.240.131            : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by wojtek0806** [comment] 2018-12-05 11:56
@tizianorosato 

the **ALL** option means everything that the module can gather, it does not do selection of modules you have installed. The expectation is for the user to comment out the facts for unused modules when **ALL** option is used. This is working as intended, I hope this helps

**Comment by tizianorosato** [comment] 2018-12-05 12:03
well , at least it should be better described in the docs.
And in my opinion options like all-ltm and all-gtm and similar for future modules could be useful.

Thanks

**Comment by caphrim007** [comment] 2018-12-05 17:12
I disagree. We do this form of checking for ASM related stuff. "all" means attempt to get al things. if it is not provisioned, then it will just be skipped. Reopening

**Comment by caphrim007** [comment] 2018-12-05 17:13
Here's how we do it for asm

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_device_facts.py#L6295

**Comment by caphrim007** [comment] 2018-12-05 17:16
@tizianorosato this should, however, be fixed already in the module in this repo. Have you tried to reproduce this error with teh `f5devcentral.f5ansible` role? https://galaxy.ansible.com/f5devcentral/f5ansible

**Comment by caphrim007** [comment] 2018-12-05 17:18
This should be fixed already. I addressed this a month ago via this patch here https://github.com/F5Networks/f5-ansible/commit/7caaea40af3d42ae696422ed919e27c48232c24e

@tizianorosato try the role I linked and it should work as expected. If it continues to be an issue, drop a note here

**Comment by caphrim007** [comment] 2018-12-05 17:19
btw, the content of that role is what will ship with ansible 2.8, so you can alternatively wait for the ansible 2.8 release to get the fix

**Closed by caphrim007** 2018-12-05 17:18 UTC
Labels: bug-report

**Comment by tizianorosato** [comment] 2018-12-05 18:16
@caphrim007 I'll try soon tomorrow the role f5devcentral.f5ansible

**Comment by tizianorosato** [comment] 2018-12-06 12:45
> @caphrim007 I'll try soon tomorrow the role f5devcentral.f5ansible
working as expected

**Comment by wojtek0806** [comment] 2018-12-06 12:48
@tizianorosato we are glad this helped, we will be adding some more ASM specific items into the facts, stay tuned :)
