### ISSUE TITLE
bigip_static_route does not take route domain

### ISSUE THREAD

**Issue by person50002** [F5Networks/f5-ansible#645] opened 2018-02-28 20:07 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_static_route

##### ANSIBLE VERSION

```
"ansible 2.5.0rc1
  config file = /projects/add_route/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0rc1-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
"
```

##### PYTHON VERSION

```
"Python 2.7.12"
```

##### BIGIP VERSION

```
"Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
"
```

##### LIBRARY VERSIONS

```
"bigsuds==1.0.6
f5-sdk==3.0.11
"
```

##### CONFIGURATION

"inventory      = hosts.yml"
##### OS / ENVIRONMENT

16.04.1-Ubuntu
##### SUMMARY

this looks similar to https://github.com/F5Networks/f5-ansible/pull/305 netaddr mistakenly given IP address including route domain
##### STEPS TO REPRODUCE

```
"---
- hosts: all

  vars_prompt:

    - name: "LTM_USER"
      prompt: "LTM username?"
      private: no
    - name: "LTM_PASS"
      prompt: "LTM passoword?"

  tasks:

    - name: "add route"
      bigip_static_route:
        server: "{{MGMT_IP}}"
        user: "{{LTM_USER}}"
        password: "{{LTM_PASS}}"
        validate_certs: no
        name: "test route"
        destination: "10.10.10.10%10"
        netmask: "255.255.255.255"
        gateway_address: "11.11.11.11%10"
"
```

##### EXPECTED RESULTS

create route
##### ACTUAL RESULTS

```
"PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [bigip1]

TASK [add route] **************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'validate_certs' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
**fatal: [bigip1]: FAILED! => {"changed": false, "msg": "The provided gateway_address is not an IP address"}**
	to retry, use: --limit @/projects/add_route/add_route.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
bigip1                     : ok=1    changed=0    unreachable=0    failed=1   
"
```

**Comment by caphrim007** [comment] 2018-03-25 04:55
@person50002 you dont supply route domains in the IP address, you supply them in the `route_domain` field of the module

https://github.com/ansible/ansible/blob/stable-2.5/lib/ansible/modules/network/f5/bigip_static_route.py#L63

**Comment by caphrim007** [comment] 2018-03-25 04:55
closing as not a bug

**Comment by caphrim007** [comment] 2018-06-28 00:49
@person50002 never heard back from you on this. if you think this is still an issue, please let us know.

**Closed by caphrim007** 2018-06-28 00:49 UTC
Labels: medium

**Comment by onurbrc** [comment] 2018-09-12 15:30
Hello @caphrim007 , 

I'm trying to create a static route within a partition and a route domain, but I don't have the same result as the CLI. 
My context : 
- Partition: internet
- Route domain: 2 created in the partition internet. 

Playbook : 
tasks:
    - name: Creating a default static route
      bigip_static_route:
        destination: 0.0.0.0
        netmask: 0.0.0.0
        gateway_address: 10.10.5.254
        partition: "{{ PARTITION }}"
        route_domain: 2
        name: default
        password: "{{ bigip_password }}"
        server: "{{ bigip_hostname }}"
        user: "{{ bigip_user }}"
        validate_certs: no
      delegate_to: localhost

CLI : (Active)(/internet)(tmos)# create net route default gw 10.10.5.254%2


Is there any difference between the syntax of the playbook and this command above ? 
When I try to execute the playbook I always get the stdout : 

 FAILED! => {"changed": false, "msg": "400 Unexpected Error: Bad Request for uri: https://@IP:443/mgmt/tm/net/route/\nText: u'{\"code\":400,\"message\":\"01070330:3: Static route gateway 10.10.5.254 is not directly connected via an interface.\",\"errorStack\":[],\"apiError\":3}'"}

However, I can pass the creation over CLI, the static route is created : 
(/internet)(tmos)# list net route
net route default {
    gw 10.10.5.254%2
    network default
    partition internet
}

Moreover, the selfip is in the same subnet domain. 
Any Help ?
Best regards, 
BC
