### ISSUE TITLE
bigip_asm_policy_manage fails to activate policy on second use

### ISSUE THREAD

**Issue by mjmenger** [F5Networks/f5-ansible#1730] opened 2020-04-22 23:44 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_asm_policy_manage

##### ANSIBLE VERSION
```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/myansible/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/myansible/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### PYTHON VERSION
```
Python 3.6.9
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.2
  Build       0.0.9
  Edition     Point Release 2
  Date        Fri Mar 20 21:06:24 PDT 2020
Kernel
  Type        Linux
  Release     3.10.0-862.14.4.el7.ve.x86_64
```

##### CONFIGURATION
roles_path = ./roles
playbooks_dir = ./
retry_files_enabled = False
host_key_checking=False
inventory= ./azure_rm.yml
action_warnings=False

##### OS / ENVIRONMENT
Running Ansible from Ubuntu 18.04

##### SUMMARY
Configuring ASM policies using bigip_asm_policy_import followed by bigip_asm_policy_manage to activate the new policy. When running the playbook any time after the first run with updated policies, the policies are uploaded but are in a deactivated state.

##### STEPS TO REPRODUCE

```
    - name: Import Security Policy
      bigip_asm_policy_import:
        name: "{{ item | basename | regex_replace('.xml') }}"
        source: "{{ item }}"
        force: yes
        provider: "{{ provider }}"
      with_fileglob:
        - "{{ git_repo_path }}/*.xml"

    - name: Activate Security Policy
      bigip_asm_policy_manage:
        name: "{{ item | basename | regex_replace('.xml') }}"
        active: yes
        state: present
        provider: "{{ provider }}"
      with_fileglob:
        - "{{ git_repo_path }}/*.xml"
```

##### EXPECTED RESULTS
Every time the playbook runs, the new policy is uploaded and activated.

##### ACTUAL RESULTS
The playbook completes successfully. However, when looking at the impacted BIG-IPs, the policies are not active.

```

```

**Comment by focrensh** [comment] 2020-04-22 23:52
Duplicate of #1654 . Leaving this issue open for now to understand potential impact of the workaround.

**Comment by wojtek0806** [comment] 2020-04-23 00:47
policy import is not idempotent cause you re using force: yes this causes your plays to change

**Comment by wojtek0806** [comment] 2020-04-23 01:08
a quick guess is that the policy remains in changes pending state if that is the case then there is a value called ‘isModified’ that indicates if the policy is Pending Apply. This is purely v14 and above behaviour, ‘active:yes’ parameter was meant to be used to activate policy in the old sense before v14 changed this. if api was updated to reflect this new behaviour we can consider a new setting for asm_policy_manage.

**Comment by mjmenger** [comment] 2020-05-01 17:51
I'm concerned that with the current workaround, there is a non-trivial window of time in which there isn't an active ASM policy on the virtual server.

**Comment by focrensh** [comment] 2020-05-01 19:08
@wojtek0806 , we need an apply option on top of active. Setting a policy to Active will set initial Apply, but additional changes need a call specifically to Apply.

```
POST https://192.168.25.42/mgmt/tm/asm/tasks/**apply-policy**

{
"policyReference": {
"link":
"https://localhost/mgmt/tm/asm/policies/vagoQLF6uOoBKvS8h3C19w"
}
}
```

The response to the request contains the following data:
```
{
"id": "oqNah2PxtwwE4YyAHGekNQ",
"kind": "tm:asm:tasks:apply-policy:applypolicytaskstate",
"policyReference": {
"link":
"https://localhost/mgmt/tm/asm/policies/vagoQLF6uOoBKvS8h3C19w"
},
"lastUpdateMicros": 1370459678272126,
"status": "NEW",
"selfLink":
"https://localhost/mgmt/tm/asm/tasks/apply-policy/oqNah2PxtwwE4YyAHGekNQ",
"startTime": "2013-06-05T15:14:36-04:00"
}
```


2. To determine the status of the apply policy operation, make a GET request to the same namespace.
```
GET https://192.168.25.42/mgmt/tm/asm/tasks/apply-policy
```
The response to the request contains the following data:.
```
{
"id": "oqNah2PxtwwE4YyAHGekNQ",
"kind": "tm:asm:tasks:apply-policy:applypolicytaskstate",
"policyReference": {
"link":
"https://localhost/mgmt/tm/asm/policies/vagoQLF6uOoBKvS8h3C19w"
},
"lastUpdateMicros": 1370459678272126,
"status": "COMPLETED",
...
}
```

**Comment by wojtek0806** [comment] 2020-05-01 21:12
we are already applying policy, you mean apply policy during update?

**Comment by focrensh** [comment] 2020-05-01 21:13
Apply if it is not currently applied (even on update). Even if this means having a new param.

**Comment by wojtek0806** [comment] 2020-05-01 21:17
has the API been updated to reflect this change in behaviour ?
apply policy applies policy if the v14 changed it then what is the new endpoint we should be using?

**Comment by wojtek0806** [comment] 2020-05-01 21:20
from the original description it seems the policy needs to be activated when updating from a changed file, so this is what we should focus on

**Comment by focrensh** [comment] 2020-05-04 14:38
Tracking with FMFA-439

**Closed** 2020-05-10 18:40 UTC
Labels: needs-triage, question
