### ISSUE TITLE
Pool is not associated with new GTM wideip when using bigip_gtm_wide_ip

### ISSUE THREAD

**Issue by rainierpineda2** [F5Networks/f5-ansible#311] opened 2017-08-22 14:10 UTC
ISSUE TYPE
 - Bug Report
 -

COMPONENT NAME
bigip_gtm_wide_ip

ANSIBLE VERSION
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]

##### PYTHON VERSION
Python 2.7.6

BIGIP VERSION
12.1.2 HF1

CONFIGURATION
library        = /usr/share/ansible/

OS / ENVIRONMENT
Linux labanos 3.13.0-128-generic #177-Ubuntu SMP i686 GNU/Linux

SUMMARY
When using the module bigip_gtm_wide_ip, I'm unable to associate an existing pool to it.

STEPS TO REPRODUCE

  tasks:
  - name: Create new GTM pool
    local_action: >
      bigip_gtm_pool
      server=10.0.1.135
      user=ansible
      password="{{ setup_password }}"
      name=test_vip1
      state=present
      type=a
      validate_certs=no
  - name: Create new wide IP
    local_action: >
      bigip_gtm_wide_ip
      server=10.0.1.135
      user=ansible
      password="{{ setup_password }}"
      lb_method=global_availability
      wide_ip=my-wide-ip.pinedax.com
      state=present
      type=a
      validate_certs=no

EXPECTED RESULTS
The pool and the wideip are created just fine. There is no option to associate the pool created with the wideip so I don't see it when i run tmsh list gtm wideip for my-wide-ip.pinedax.com

gtm wideip a my-wide-ip.pinedax.com {
    pool-lb-mode global-availability
}
gtm wideip a test_vip_global.pinedax.com {
    aliases {
        test_vip.pinedax.com
    }
    pools {
        test_vip1 {
            order 0
        }
    }
}

##### ACTUAL RESULTS
ansible-playbook 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: addf5wip.yml **********************************************************************************
1 plays in addf5wip.yml
Enter password: 

PLAY [F5 Configure new wide IP] *************************************************************************
META: ran handlers

TASK [Create new GTM pool] ******************************************************************************
task path: /home/apineda/ansible/playbooks/addf5wip.yml:17
ok: [localhost -> localhost] => {"changed": false, "failed": false}

TASK [Create new wide IP] *******************************************************************************
task path: /home/apineda/ansible/playbooks/addf5wip.yml:27
[DEPRECATION WARNING]: The provided lb_method is deprecated.
This feature will be removed in version 
2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost -> localhost] => {"changed": false, "failed": false}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

**Comment by WRJFontenot** [comment] 2018-03-06 18:24
Just ran into this same problem when trying to configure my GTM servers.  Doesn't look like it's going to be fixed in 2.5.  Please make this a priority for 2.6.

**Comment by WRJFontenot** [comment] 2018-03-06 18:30
Is this a dupe of #124 ?

**Comment by caphrim007** [comment] 2018-03-13 06:54
fixed in #124 afaik. closing

**Closed by caphrim007** 2018-03-13 06:54 UTC
Labels: enhancement, high

**Comment by rainierpineda2** [comment] 2018-03-13 20:54
Thanks Tim. So in order for me to use this do I have to be in Ansible 2.5? Right now our system is 2.4 and I don’t know when we’ll move to 2.5. It seems I cannot just copy the module into my library directory because it is looking for other dependent files.

TASK [Create WideIP] *************************************************************************************
fatal: [labusra5474lb005]: FAILED! => {"failed": true, "msg": "Could not find imported module support code for bigip_gtm_wide_ip.  Looked for either F5Client.py or bigip.py"}

**Comment by caphrim007** [comment] 2018-03-14 03:25
@rainierpineda2 the module, according to the projects link on the right, requires the next next version of ansible (what is currently devel) 2.6.

When 2.5 was feature frozen, we immediately began work on 2.6 and this is part of that work.

To backport a 2.6 module to 2.4 will require some legwork as ansible raises errors when one of the module dependencies is not found. I dont have a document immediately available that describes the process
