### ISSUE TITLE
bigip_static_route fails on default routes subsequent calls

### ISSUE THREAD

**Issue by BenoitLarouche** [F5Networks/f5-ansible#752] opened 2018-06-11 19:49 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_static_route

##### ANSIBLE VERSION
```
ansible 2.6.0rc1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/blarouch/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION
```
Python 2.7.12
```

##### BIGIP VERSION
```
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.14
```

##### SUMMARY
bigip_static_route is broken when called for a second time on a Default static route (0.0.0.0/0). The first-time creation works fine, but when the task is called a second time, it fails during the current destination value check.

##### STEPS TO REPRODUCE
Run the following bigip_static_route task two times, changing the `gateway_address` based on your config.

```
- name: Create DefaultRoute
  bigip_static_route:
    destination: 0.0.0.0
    netmask: 0
    gateway_address: 172.25.88.106
    name: DefaultRoute
    partition: Part_Ilb
    provider: "{{ provider }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS
First call creates the Default static route, every other subsequent call returns a simple success.

##### ACTUAL RESULTS
First call does create the Default static route with 0.0.0.0/0, but the subsequent calls fails with the following error:

```
The full traceback is:
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 619, in main
    results = mm.exec_module()
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 451, in exec_module
    changed = self.present()
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 482, in present
    return self.update()
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 514, in update
    if not self.should_update():
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 507, in should_update
    result = self._update_changed_options()
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 431, in _update_changed_options
    change = diff.compare(k)
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 365, in compare
    result = getattr(self, param)
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 383, in destination
    if self.want.destination_ip != self.have.destination_ip:
  File "/tmp/ansible_jmqtjf/ansible_module_bigip_static_route.py", line 337, in destination_ip
    "The provided destination is not an IP address"

fatal: [f1252ntlabilbtesta2 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "description": null,
            "destination": "0.0.0.0",
            "gateway_address": "172.25.88.106",
            "mtu": null,
            "name": "DefaultRoute",
            "netmask": "0",
            "partition": "Part_Ilb",
            "password": null,
            "pool": null,
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "reject": null,
            "route_domain": null,
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null,
            "vlan": null
        }
    },
    "msg": "The provided destination is not an IP address"
}
```

**Comment by BenoitLarouche** [comment] 2018-06-11 19:58
Looks a lot like [issue 104](https://github.com/F5Networks/f5-ansible/issues/104), I'm not sure what's the difference here, beside the partition.

**Comment by caphrim007** [comment] 2018-06-11 21:14
@BenoitLarouche I can't reproduce this error. are you sure you have the right version of the module and that it is actually being used?

can you provide the REST API output for this static route?

`curl -k -u admin:admin https://BIGIP/mgmt/tm/net/route/~Part_Ilb~DefaultRoute`

**Comment by BenoitLarouche** [comment] 2018-06-12 13:53
@caphrim007  I'm pretty sure I'm using the module directly installed from pip.

The curl request returns:
```
$ curl -k -u admin:admin https://10.55.213.6/mgmt/tm/net/route/~Part_Ilb~DefaultRoute --noproxy "*"

{"kind":"tm:net:route:routestate","name":"DefaultRoute","partition":"Part_Ilb","fullPath":"/Part_Ilb/DefaultRoute","generation":6264,"selfLink":"https://localhost/mgmt/tm/net/route/~Part_Ilb~DefaultRoute?ver=13.1.0.7","gw":"172.25.88.106%100","mtu":0,"network":"default%100"}
```

**Comment by delgadillo22** [comment] 2018-06-15 23:02
FMFA-163

**Comment by rabru** [comment] 2018-07-30 13:55
I run into the same  issue, even without changing the IP address. In the moment the route was already created, it fails with this error message. If I delete the route and start the playbook again, it works fine.

If I use routedomain 0 and partiton "Common" it works fine, but if I change them, I run into this issue. 

Here is my environment:
```
python 2.7.9
bigsuds 1.0.6
f5-sdk 3.0.18
ansible 2.6.1 
```

Can you please investigate.
Thanks

**Comment by caphrim007** [comment] 2018-08-11 18:37
@BenoitLarouche @rabru I have reason to believe, based off your provided examples, that this is now fixed. please take a look if you have the time.

**Closed** 2018-08-11 18:36 UTC
Labels: bug-report, high
