### ISSUE TITLE
bigip_command stdout should always return tmsh's stdout

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#624] opened 2018-02-13 09:56 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_command

##### ANSIBLE VERSION
Ansible Tower 3.1.5

```
(ansible)[root@rhel74-1-ucamaro vcpe]# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### PYTHON VERSION

```
(ansible)[root@rhel74-1-ucamaro ~]# python -V
Python 2.7.5
```

##### BIGIP VERSION

```
[root@atom-bigip:Active:Standalone] config # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
[root@towermstr tasks]# pip freeze | egrep '(f5-sdk|bigsuds)'
bigsuds==1.0.6
f5-sdk==3.0.5
```

##### SUMMARY

bigip_command should return on stdout the last output from the command execution rather than diagnostic messages from the bigip_command itself. 

##### STEPS TO REPRODUCE

The debug task below shows on stdout ```fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": {"changed": false, "failed": true, "msg": "One or more conditional statements have not been satisfied"}}``` which is not useful at all. It should return the last output from the command instead.

```
- name: "Wait until CC has completed deleting all the configuration"
  bigip_command:
    commands: list ltm node /blahblah
    password: "{{ bigip_adminpass }}"
    server: "{{ bigip_server }}"
    user: "{{ bigip_user }}"
    validate_certs: "no"
    interval: 5
    retries: 2
    wait_for: stdout == ""
  ignore_errors: true
  delegate_to: localhost
  register: stdout

- name: "Print stdout"
  debug:
    msg: "{{ stdout }}"
  delegate_to: localhost

```

**Comment by caphrim007** [comment] 2018-02-14 02:32
@alonsocamaro this module does always return stdout. Ansible suppresses this output though unless you run with `-vvvv`.

The output, if there is any, is stored in 2 variables for the users convenience.

One, is called `stdout`. In your example, it would be referenced like this `{{ stdout['stdout'] }}` because you registered a variable named `stdout` and the brackets because the name `stdout` is what the module returns. It is a list of lines of output.

An example,

```
    "stdout": [
        "\nSys::Version\nMain Package\n  Product     BIG-IP\n  Version     13.1.0\n  Build       0.0.1868\n  Edition     Final\n  Date        Fri Nov 10 17:27:22 PST 2017\n\n"
    ],
```

The second return value is `stdout_lines`. This is a list, containing sublists of each line. The sublist is split up by the line terminator; `"\n"`. This is a slightly more complicated output. It is better for situations where you might want to map over the return values.

An example,

```
    "stdout_lines": [
        [
            "",
            "Sys::Version",
            "Main Package",
            "  Product     BIG-IP",
            "  Version     13.1.0",
            "  Build       0.0.1868",
            "  Edition     Final",
            "  Date        Fri Nov 10 17:27:22 PST 2017",
            "",
            ""
        ]
    ]
```

**Comment by caphrim007** [comment] 2018-03-05 01:18
closing as not a bug

**Closed by caphrim007** 2018-03-05 01:18 UTC
Labels: not-a-bug
