### ISSUE TITLE
bigip_command stripping tmsh

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-ansible#60] opened 2017-01-04 08:50 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_command

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.2.0.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
# python -V
Python 2.7.6

```

##### BIGIP VERSION

```
# tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       2.0.204
  Edition     Hotfix HF2
  Date        Fri Oct 21 17:35:48 PDT 2016

Hotfix List
ID613127-3    ID609325    ID598294-2  ID607857-1  ID608373-2  ID590578-4
ID603997      ID599033-3  ID622529    ID575170-5  ID575170-2  ID601927-1
ID604459-1    ID600859-3  ID604211-4  ID434573-6  ID585120-1  ID624264-2
ID603605-1    ID606110-4  ID590578-5  ID542097-3  ID589318-2  ID513851-2
ID594910-4    ID597309-2  ID585366-2  ID605314-2  ID603997-3  ID602653-3
ID561444-1    ID607200-1  ID590074-1  ID597708-4  ID601938-8  ID599769-1
ID600778-1    ID596674-1  ID608373-1  ID600778-2  ID606509-1  ID595394-2
ID605682-2    ID595394-4  ID623048    ID612952-1  ID598294-1  ID593355
ID596814-5    ID592716-1  ID606110-3  ID585366    ID599054-2  ID605682-3
ID614599      ID595064-1  ID601309    ID593355-2  ID513851-3  ID527403-1
ID618382-4    ID590608-1  ID589318-1  ID612564    ID599033-4  ID521270-1
ID610307      ID590608-3  ID606807-1  ID590074-2  ID599068-2  ID589149-2
ID595064-2    ID600859-4  ID606509-3  ID601938-2  ID585120-2  ID321971-1
ID594910-1    ID599769    ID599068-3  ID609677-1  ID599054-4  ID603605-2
ID604211-3    ID596814-9  ID602061    ID601927-8
```

##### CONFIGURATION

Uncommented below due to some errors with .ssh/known_hosts error in tower
----snip----
# uncomment this to disable SSH key host checking
host_key_checking = False
----snip----

##### OS / ENVIRONMENT

Ubuntu 14.04.2 LTS

##### SUMMARY

Need to add two tmsh like "tmsh tmsh show sys version" or else following will result:
----snip----
TASK [bigip_command : debug] *************************************************** ok: [172.28.15.116] => {
    "result.stdout_lines": [
        [
            "-bash: show: command not found"
        ]
    ]
}
----snip----

##### STEPS TO REPRODUCE

1. Setup Ansible Tower 3.0.3 using 
2. Configure Inventory, credentials, and Job Template to talk to BIG-IP
3. Grab the playbooks from https://github.com/F5Networks/f5-ansible 
4. Modify playbook for outputting to stdout_lines
5. Run Job, note the bash error

```
- name: Test the bigip_command module
  hosts: bigips
  connection: local

  vars:
      cli:
          host: "{{ inventory_hostname }}"
          username: root
          password: default
#          port: 2222
  tasks:
    - name: Run show version on remote devices
      bigip_command:
          commands:
              - tmsh tmsh show sys version
          provider: "{{ cli }}"
      register: result
    - debug: var=result.stdout_lines

  roles:
      - bigip_command
```

##### EXPECTED RESULTS

Std out should look like below:

TASK [Run show version on remote devices] ************************************** ok: [172.28.15.116] TASK [debug] ******************************************************************* ok: [172.28.15.116] => {
    "result.stdout_lines": [
        [
            "", 
            "Sys::Version", 
            "Main Package", 
            "  Product     BIG-IP", 
            "  Version     12.1.1", 
            "  Build       2.0.204", 
            "  Edition     Hotfix HF2", 
            "  Date        Fri Oct 21 17:35:48 PDT 2016", 
            "", 
            "Hotfix List", 
            "ID613127-3    ID609325    ID598294-2  ID607857-1  ID608373-2  ID590578-4", 
            "ID603997      ID599033-3  ID622529    ID575170-5  ID575170-2  ID601927-1", 
            "ID604459-1    ID600859-3  ID604211-4  ID434573-6  ID585120-1  ID624264-2", 
            "ID603605-1    ID606110-4  ID590578-5  ID542097-3  ID589318-2  ID513851-2", 
            "ID594910-4    ID597309-2  ID585366-2  ID605314-2  ID603997-3  ID602653-3", 
            "ID561444-1    ID607200-1  ID590074-1  ID597708-4  ID601938-8  ID599769-1", 
            "ID600778-1    ID596674-1  ID608373-1  ID600778-2  ID606509-1  ID595394-2", 
            "ID605682-2    ID595394-4  ID623048    ID612952-1  ID598294-1  ID593355", 
            "ID596814-5    ID592716-1  ID606110-3  ID585366    ID599054-2  ID605682-3", 
            "ID614599      ID595064-1  ID601309    ID593355-2  ID513851-3  ID527403-1", 
            "ID618382-4    ID590608-1  ID589318-1  ID612564    ID599033-4  ID521270-1", 
            "ID610307      ID590608-3  ID606807-1  ID590074-2  ID599068-2  ID589149-2", 
            "ID595064-2    ID600859-4  ID606509-3  ID601938-2  ID585120-2  ID321971-1", 
            "ID594910-1    ID599769    ID599068-3  ID609677-1  ID599054-4  ID603605-2", 
            "ID604211-3    ID596814-9  ID602061    ID601927-8", 
            ""
        ]
    ]
}

##### ACTUAL RESULTS

```
SSH password: PLAY [Test the bigip_command module] ******************************************* TASK [setup] ******************************************************************* ok: [172.28.15.116] TASK [bigip_command : Run show version on remote devices] ********************** ok: [172.28.15.116] TASK [bigip_command : debug] *************************************************** ok: [172.28.15.116] => {
    "result.stdout_lines": [
        [
            "-bash: show: command not found"
        ]
    ]
} TASK [bigip_command : Run show sys clock] ************************************** ok: [172.28.15.116] TASK [bigip_command : debug] *************************************************** ok: [172.28.15.116] => {
    "result.stdout_lines": [
        [
            "-bash: show: command not found"
        ]
    ]
} TASK [bigip_command : Run list auth] ******************************************* ok: [172.28.15.116] TASK [bigip_command : debug] *************************************************** ok: [172.28.15.116] => {
    "result.stdout_lines": [
        [
            "-bash: list: command not found"
        ]
    ]
} 
----snip----
```

**Comment by tkam8** [comment] 2017-01-04 09:03
This is my first run with ansible tower, yet along ansible. If I am missing anything basic, please let me know. I am also not a python expert so unable to efficiently decipher below code related to tmsh prefix. 

https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_command.py

FYI: the fix for the .ssh/known_hosts issue in tower was resolved by: https://github.com/ansible/ansible-modules-core/issues/5316

**Comment by caphrim007** [comment] 2017-01-04 20:34
@tkam8 i see an extra `tmsh` in your task there. Was that intentional?

**Comment by tkam8** [comment] 2017-01-05 01:09
> @caphrim007 yes, this was intentional. Let me summarize what I see going on:
> 
> After running my playbook, standard out also shows the tasks in below playbook also run:
> 
> /var/lib/awx/projects/_10__f5playbooks_project2/roles/bigip_command/tasks/issue-54.yaml
> 
> I modified those tasks to also output to stdout_lines...
> 
> ```
> - name: Run show version on remote devices
>   bigip_command:
>       commands:
>           - tmsh show sys version
>       provider: "{{ cli }}"
>   register: result
> - debug: var=result.stdout_lines
> 
> - name: Run show sys clock
>   bigip_command:
>       commands:
>           - "tmsh show sys clock"
>       provider: "{{ cli }}"
>   register: result
> - debug: var=result.stdout_lines
> 
> - name: Run list auth
>   bigip_command:
>       commands:
>           - "tmsh list auth"
>       provider: "{{ cli }}"
>   register: result
> - debug: var=result.stdout_lines
> ```
> 
> and the output I see for those respective tasks look like this: 
> 
> 
> > TASK [bigip_command : Run show version on remote devices] **********************
> > ok: [172.28.15.116]
> > 
> > TASK [bigip_command : debug] ***************************************************
> > ok: [172.28.15.116] => {
> >     "result.stdout_lines": [
> >         [
> >             "-bash: show: command not found"
> >         ]
> >     ]
> > }
> > 
> > TASK [bigip_command : Run show sys clock] **************************************
> > ok: [172.28.15.116]
> > 
> > TASK [bigip_command : debug] ***************************************************
> > ok: [172.28.15.116] => {
> >     "result.stdout_lines": [
> >         [
> >             "-bash: show: command not found"
> >         ]
> >     ]
> > }
> > 
> > TASK [bigip_command : Run list auth] *******************************************
> > ok: [172.28.15.116]
> > 
> > TASK [bigip_command : debug] ***************************************************
> > ok: [172.28.15.116] => {
> >     "result.stdout_lines": [
> >         [
> >             "-bash: list: command not found"
> >         ]
> >     ]
> > }
> 
> This error is similar to what you would get if you try to issue a show command outside of tm shell like so:
> 
> ```
> [root@bigip1-ansible:Active:Standalone] config # show sys version
> -bash: show: command not found
> ```
> 
> So I thought, what would happen if I added a tmsh in there and when I tried it for my playbook, the output was displayed correctly:
> 
> TASK [Run show version on remote devices] **************************************
> ok: [172.28.15.116]
> 
> TASK [debug] *******************************************************************
> ok: [172.28.15.116] => {
>     "result.stdout_lines": [
>         [
>             "", 
>             "Sys::Version", 
>             "Main Package", 
>             "  Product     BIG-IP", 
>             "  Version     12.1.1", 
>             "  Build       2.0.204", 
>             "  Edition     Hotfix HF2", 
>             "  Date        Fri Oct 21 17:35:48 PDT 2016", 
>             "", 
>             "Hotfix List", 
>             "ID613127-3    ID609325    ID598294-2  ID607857-1  ID608373-2  ID590578-4", 
>             "ID603997      ID599033-3  ID622529    ID575170-5  ID575170-2  ID601927-1", 
>             "ID604459-1    ID600859-3  ID604211-4  ID434573-6  ID585120-1  ID624264-2", 
>             "ID603605-1    ID606110-4  ID590578-5  ID542097-3  ID589318-2  ID513851-2", 
>             "ID594910-4    ID597309-2  ID585366-2  ID605314-2  ID603997-3  ID602653-3", 
>             "ID561444-1    ID607200-1  ID590074-1  ID597708-4  ID601938-8  ID599769-1", 
>             "ID600778-1    ID596674-1  ID608373-1  ID600778-2  ID606509-1  ID595394-2", 
>             "ID605682-2    ID595394-4  ID623048    ID612952-1  ID598294-1  ID593355", 
>             "ID596814-5    ID592716-1  ID606110-3  ID585366    ID599054-2  ID605682-3", 
>             "ID614599      ID595064-1  ID601309    ID593355-2  ID513851-3  ID527403-1", 
>             "ID618382-4    ID590608-1  ID589318-1  ID612564    ID599033-4  ID521270-1", 
>             "ID610307      ID590608-3  ID606807-1  ID590074-2  ID599068-2  ID589149-2", 
>             "ID595064-2    ID600859-4  ID606509-3  ID601938-2  ID585120-2  ID321971-1", 
>             "ID594910-1    ID599769    ID599068-3  ID609677-1  ID599054-4  ID603605-2", 
>             "ID604211-3    ID596814-9  ID602061    ID601927-8", 
>             ""
>         ]
>     ]
> }
> 


any hints or am I doing something wrong?

**Comment by tkam8** [comment] 2017-01-05 02:47
[job_38.txt](https://github.com/F5Networks/f5-ansible/files/686303/job_38.txt)

attaching -vvv std out  for clues

**Comment by caphrim007** [comment] 2017-01-05 05:10
@tkam8 can you manually log in as the user that you are using in these playbooks and post here the full content of the cli status prompt?

For example,

`[root@localhost:Active:Standalone config #`

**Comment by tkam8** [comment] 2017-01-05 05:17
Ansible Tower:
root@DCM-NTP:/var/lib/awx/projects/_10__f5playbooks_project2/playbooks# 

BIGIP:
[root@bigip1-ansible:Active:Standalone] config #

**Comment by caphrim007** [comment] 2017-01-19 04:00
@tkam8 I believe this is now fixed. Please test with the updated command module.

**Comment by caphrim007** [comment] 2017-01-19 04:08
I believe this issue has been recently fixed in the repo here. If you can check the updated code to make sure that it addresses the issue you were seeing, I'd appreciate it.

If the problem is still apparent, please file a new issue

**Closed by caphrim007** 2017-01-19 04:08 UTC
