### ISSUE TITLE
bigip_ssl_certificate not uploading complete filename

### ISSUE THREAD

**Issue by hanej** [F5Networks/f5-ansible#58] opened 2016-12-23 16:13 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_ssl_certificate

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.2
  Build    0.0.141
  Edition  Final
  Date     Fri Jan 30 14:50:39 PST 2015
```

##### SUMMARY

When specifying cert_content, key_content, cert_src, or key_src the files on the F5 are not getting the .key or .crt appended to the certificate name.  This is resulting in duplicate certs on the F5 from a GUI standpoint and either one cannot be deleted.

##### STEPS TO REPRODUCE

```
---
- name: Prepare F5 for SSL Certificate Upload
  hosts: ltm
  remote_user: ansible
  gather_facts: false

  vars_files:
    - vars/secrets.yml

  tasks:
    # This is needed or the upload fails
    - name: ensure download directory exists
      raw: "mkdir -p /var/config/rest/downloads/tmp/"


- name: Upload SSL Certificates to LTMs
  hosts: ltm
  remote_user: root
  gather_facts: false

  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Import PEM Certificate
      bigip_ssl_certificate:
        name: "wildcard_ftscc_net"
        server: "{{ ansible_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        state: "present"
        validate_certs: false
        cert_content: "{{ cert content goes here }}"
        key_content: "{{ key content goes here }}"
      delegate_to: "{{ jump_server }}"
```

```
ansible-playbook -i inventory/hosts -e "cert_file=wildcard_ftscc_net.yml" --vault-password-file ~/.vault_password import_ssl_cert.yml
```

##### EXPECTED RESULTS

The existing key that was uploaded via GUI was overwritten with new version.

##### ACTUAL RESULTS

A duplicate key was installed without the file extension resulting in 2 of the same SSL certs visible through the GUI.  The certificates below with the 49524 extension was uploaded through the GUI and is the old version.  The 75278 extension was done through Ansible.  The Ansible version should have overwritten the existing version.

```
[ root@f5 /config/filestore/files_d/Common_d]# find . -name "*ftscc*"
./certificate_key_d/:Common:wildcard_ftscc_net_75278_1
./certificate_key_d/:Common:wildcard_ftscc_net.key_49524_2
./certificate_d/:Common:wildcard_ftscc_net_75276_1
./certificate_d/:Common:wildcard_ftscc_net.crt_49528_2
```

**Comment by hanej** [comment] 2016-12-23 16:15
![f5 bug](https://cloud.githubusercontent.com/assets/185708/21457977/1cb59e6e-c901-11e6-872f-128245a36638.jpeg)

**Comment by caphrim007** [comment] 2017-01-16 21:01
@hanej I have a fix for this, and am hoping to have the code made available soon

**Comment by mcgonagle** [comment] 2017-05-27 02:16
https://github.com/mcgonagle/ansible_f5/issues/12

**Comment by caphrim007** [comment] 2017-05-27 02:26
@mcgonagle have you tried the code in this repo? @hanej 's problem should be fixed

**Comment by caphrim007** [comment] 2017-06-20 02:53
this should now be complete. if there are further issues, please open a new issue.

**Closed by caphrim007** 2017-06-20 02:53 UTC
Labels: bug-report

**Comment by m2harshanalore** [comment] 2018-08-08 13:54
@caphrim007  - I'm using ansible v2.4 and i'm unable to pass the content of cert and key through this module. It says "unable to validate certificate, invalid x509 file" . However i'm able to install the cert and key when i import it directly through F5 GUI. Appreciate if you can suggest anything.

**Comment by caphrim007** [comment] 2018-08-08 14:12
@m2harshanalore did you generate the cert with a specific command? something that I could reproduce?

**Comment by m2harshanalore** [comment] 2018-08-08 14:25
No i didn't . The user of the specific application has this cert and key content. We just pass the content through the variable.

**Comment by m2harshanalore** [comment] 2018-08-10 15:07
@caphrim007  : Hey i did find where the issue is , the name parameter in the module won't accept special characters. If you could assist me fix that , it would be of great help.

**Comment by m2harshanalore** [comment] 2018-08-20 10:52
This works fine for me :- 
  
  - set_fact:
        cert_name: "{{ fqdn }}.crt"
    - set_fact:
        key_name: "{{ fqdn }}.key"

    - name: Upload the cert to the LTM
      bigip_ssl_certificate:
        name: "{{ cert_name }}"

    - name: Upload the key to the LTM
      bigip_ssl_key:
        name: "{{ key_name }}"

**Comment by m2harshanalore** [comment] 2018-08-20 10:54
I'm facing issue while running the bigip_http_monitor playbook in Ansible v2.6. However the code works perfectly in Ansible v2.4. Can you assist me ?

Below is the error :-: 
-> localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (bigip_monitor_http) module: _ansible_keep_remote_files,_ansible_remote_tmp,_ansible_tmpdir,provider Supported parameters include: interval,ip,name,parent,parent_partition,partition,password,port,receive,receive_disable,send,server,server_port,state,time_until_up,timeout,user,validate_certs"}
