### ISSUE TITLE
Error when running qkview module

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1951] opened 2021-01-27 00:15 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_qkview

##### ANSIBLE VERSION

```
/ansible # ansible --version
ansible 2.10.5
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Jul 19 2020, 03:57:54) [GCC 8.3.0]

```

##### PYTHON VERSION

```
3.7.7

```

##### BIGIP VERSION

```
13.1.0

```

##### OS / ENVIRONMENT

Docker container running 2.10 ansible.
The BIG-IP is a VCMP guest.

##### SUMMARY

Qkview crashes - This bug looks the same as #1831

```
- name: Fetch a qkview from the VCMP guest "{{ item }}"
  block:
    - name: Fetch qkview block
      bigip_qkview:
        dest: "{{ BACKUPS }}/{{ ITSM }}-{{ item }}.qkview"
        exclude_core: yes
        exclude: all
        provider:
          server: "{{ item }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
      delegate_to: localhost
  rescue:
    - name: fetching qkview failed, try manual and continue
      pause:
        seconds: 7200
  tags:
    - pre-upgrade-guests
```

##### EXPECTED RESULTS

qkview  downloaded

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 591, in <module>
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 584, in main
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 220, in exec_module
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 257, in exec_module
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 280, in present
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 306, in execute
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 353, in execute_on_device
  File "/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 462, in _wait_for_async_task_to_finish_on_device
KeyError: '_taskState'
fatal: [VIP2400-R43-S5.sea.pslab.local]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 591, in <module>\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 584, in main\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 220, in exec_module\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 257, in exec_module\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 280, in present\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 306, in execute\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 353, in execute_on_device\n  File \"/tmp/ansible_bigip_qkview_payload_5g6y96_0/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 462, in _wait_for_async_task_to_finish_on_device\nKeyError: '_taskState'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by grf5** [comment] 2021-01-27 17:29
I believe this is due to the fact that the Ansible module uses a default filename of localhost.localdomain.qkview on the remote host. When multiple BIG-IPs are running the same playbook, there is a chance that the same qkview download tasks will execute at/near the same time. I believe this can be addressed by adding a filename parameter with a unique filename per host.

Example:

`    - name: Fetch a qkview from the remote device
      bigip_qkview:
        filename: "{{ inventory_hostname_short }}-{{ ansible_date_time.iso8601_basic_short }}.qkview"
        dest: "{{ backup_loc }}/{{ inventory_hostname_short }}-{{ ansible_date_time.iso8601_basic_short }}.qkview"
      delegate_to: localhost
      ignore_errors: yes`

**Comment by trinaths** [comment] 2021-01-28 04:56
Create INFRAANO-170 for internal tracking.

**Comment by trinaths** [comment] 2021-02-01 09:06
Unable to reproduce the issue. Close this issue.

**Closed by trinaths** 2021-02-01 09:06 UTC

**Comment by SoumenAbhishek** [comment] 2021-07-30 07:20
@focrensh @caphrim007 can you please try with multiple hosts. I believe you should be able to reproduce the issue
