### ISSUE TITLE
bigip-vlan giving error

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#128] opened 2017-04-17 18:29 UTC
ISSUE 1
  - name: Add Internal VLAN
    bigip_vlan:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      untagged_interfaces:
       - 1.1
       - 1.2
      name: "Internal"
      tag: "11"
      validate_certs: "no"
    delegate_to: localhost

TASK [Add Internal VLAN] ********************************************************************************************************************************************************************************************************************
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The specified interface \"1.1\" was not found"}
        to retry, use: --limit @/root/ps_ansible/playbooks/bigipvlan.retry

If I give the below it works 
  - name: Add Internal VLAN
    bigip_vlan:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      untagged_interfaces: 1.1
     name: "Internal"
      tag: "11"
      validate_certs: "no"
    delegate_to: localhost
---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

ISSUE 2
For the tag , looks like I can only specify an interface and not a trunk name (is this intentional, if possible we should support this)
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "argument tag is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: 'Test'"}

- name: Add Internal VLAN
    bigip_vlan:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      #tagged_interfaces: 1.2
      untagged_interfaces: 1.1
      name: "External"
      tag: Test
      validate_certs: "no"

**Comment by wojtek0806** [comment] 2017-04-17 19:02
In the second case, the tag is set to be 'int' numerical value, it will not accept anything other than a number. I will have to look at issue 1 next.

**Comment by wojtek0806** [comment] 2017-04-17 19:11
trunks would be specified in the tagged_interfaces list, but they need to be created first on the device in order for you to be able to add them. 'tag' option is only for vlan tagging.

**Comment by wojtek0806** [comment] 2017-04-17 19:13
you are using the devel branch right ?

**Comment by payalsin** [comment] 2017-04-17 19:22
yes correct trunk would need to be created first on the bigip in order for us to tag it. Just saying if we can support adding a non int value for tagged/untagged interface it would be good. If not its ok too.

yes using the devel branch.

**Comment by wojtek0806** [comment] 2017-04-17 19:22
can you do a GET to this REST endpoint on your device and gist the output here?

https://10.192.73.218/mgmt/tm/net/interface

From what I can see the problem may lie in the response you get from the device once you reach this part of the lib:

https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_vlan.py#L240

If i get your output in the .json I can have a look at something we are missing.

**Comment by wojtek0806** [comment] 2017-04-17 19:25
you would not be able to add this as we do interface comparison on what is on the device, so the actual interface has to exist first, and interface names are strings.

**Comment by wojtek0806** [comment] 2017-04-17 19:30
can you code paste the first yaml as well please? I want to check if that indentation is not just a copy paste error :)

**Comment by wojtek0806** [comment] 2017-04-17 19:45
@payalsin  I have used same setup as you have on your yaml on my hardware box running 11.5.4 and i had no issues. This increasingly looks like a problem on the bigip of sorts.

**Comment by payalsin** [comment] 2017-04-17 20:23
Yaml code:

- name: Add Internal VLAN
    bigip_vlan:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      tagged_interfaces:
      - 1.1
      - 1.2
      name: "External"
      validate_certs: "no"
    delegate_to: localhost

Response from BIGIP

[root@mg-server1 ps_ansible]# curl -k --user admin:admin -H "Accept: application/json" -H "Content-Type:application/json" https://10.192.73.218/mgmt/tm/net/interface | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2885  100  2885    0     0   6140      0 --:--:-- --:--:-- --:--:--  6138
{
    "items": [
        {
            "bundle": "not-supported",
            "bundleSpeed": "not-supported",
            "enabled": true,
            "flowControl": "tx-rx",
            "forceGigabitFiber": "disabled",
            "forwardErrorCorrection": "not-supported",
            "fullPath": "1.1",
            "generation": 1011032,
            "ifIndex": 48,
            "kind": "tm:net:interface:interfacestate",
            "lldpAdmin": "txonly",
            "lldpTlvmap": 130943,
            "macAddress": "00:50:56:80:57:16",
            "mediaActive": "none",
            "mediaFixed": "10000T-FD",
            "mediaMax": "10000T-FD",
            "mediaSfp": "auto",
            "mtu": 1500,
            "name": "1.1",
            "preferPort": "sfp",
            "qinqEthertype": "0x8100",
            "selfLink": "https://localhost/mgmt/tm/net/interface/1.1?ver=12.1.2",
            "sflow": {
                "pollInterval": 0,
                "pollIntervalGlobal": "yes"
            },
            "stp": "enabled",
            "stpAutoEdgePort": "enabled",
            "stpEdgePort": "true",
            "stpLinkType": "auto"
        },
        {
            "bundle": "not-supported",
            "bundleSpeed": "not-supported",
            "enabled": true,
            "flowControl": "tx-rx",
            "forceGigabitFiber": "disabled",
            "forwardErrorCorrection": "not-supported",
            "fullPath": "1.2",
            "generation": 1011031,
            "ifIndex": 64,
            "kind": "tm:net:interface:interfacestate",
            "lldpAdmin": "txonly",
            "lldpTlvmap": 130943,
            "macAddress": "00:50:56:80:df:3a",
            "mediaActive": "none",
            "mediaFixed": "10000T-FD",
            "mediaMax": "10000T-FD",
            "mediaSfp": "auto",
            "mtu": 1500,
            "name": "1.2",
            "preferPort": "sfp",
            "qinqEthertype": "0x8100",
            "selfLink": "https://localhost/mgmt/tm/net/interface/1.2?ver=12.1.2",
            "sflow": {
                "pollInterval": 0,
                "pollIntervalGlobal": "yes"
            },
            "stp": "enabled",
            "stpAutoEdgePort": "enabled",
            "stpEdgePort": "true",
            "stpLinkType": "auto"
        },
        {
            "bundle": "not-supported",
            "bundleSpeed": "not-supported",
            "enabled": true,
            "flowControl": "tx-rx",
            "forceGigabitFiber": "disabled",
            "forwardErrorCorrection": "not-supported",
            "fullPath": "1.3",
            "generation": 1011024,
            "ifIndex": 80,
            "kind": "tm:net:interface:interfacestate",
            "lldpAdmin": "txonly",
            "lldpTlvmap": 130943,
            "macAddress": "00:50:56:80:f2:03",
            "mediaActive": "none",
            "mediaFixed": "10000T-FD",
            "mediaMax": "10000T-FD",
            "mediaSfp": "auto",
            "mtu": 9198,
            "name": "1.3",
            "preferPort": "sfp",
            "qinqEthertype": "0x8100",
            "selfLink": "https://localhost/mgmt/tm/net/interface/1.3?ver=12.1.2",
            "sflow": {
                "pollInterval": 0,
                "pollIntervalGlobal": "yes"
            },
            "stp": "enabled",
            "stpAutoEdgePort": "enabled",
            "stpEdgePort": "true",
            "stpLinkType": "auto"
        },
        {
            "bundle": "not-supported",
            "bundleSpeed": "not-supported",
            "enabled": true,
            "flowControl": "tx-rx",
            "forceGigabitFiber": "disabled",
            "forwardErrorCorrection": "not-supported",
            "fullPath": "mgmt",
            "generation": 1010982,
            "ifIndex": 32,
            "kind": "tm:net:interface:interfacestate",
            "lldpAdmin": "txonly",
            "lldpTlvmap": 130943,
            "macAddress": "00:50:56:80:d4:f8",
            "mediaActive": "100TX-FD",
            "mediaFixed": "auto",
            "mediaSfp": "auto",
            "mtu": 1500,
            "name": "mgmt",
            "preferPort": "sfp",
            "qinqEthertype": "0x8100",
            "selfLink": "https://localhost/mgmt/tm/net/interface/mgmt?ver=12.1.2",
            "sflow": {
                "pollInterval": 0,
                "pollIntervalGlobal": "yes"
            },
            "stp": "enabled",
            "stpAutoEdgePort": "enabled",
            "stpEdgePort": "true",
            "stpLinkType": "auto"
        }
    ],
    "kind": "tm:net:interface:interfacecollectionstate",
    "selfLink": "https://localhost/mgmt/tm/net/interface?ver=12.1.2"
}

**Comment by caphrim007** [comment] 2017-04-17 20:31
@payalsin use the triple backtick, `, to quote your yaml please

**Comment by wojtek0806** [comment] 2017-04-17 21:37
@payal can you tell me if this is a VE or hardware unit?

**Comment by payalsin** [comment] 2017-04-17 21:47
this is a VE

**Comment by wojtek0806** [comment] 2017-04-17 21:58
Ok then that explains it..i need to verify but from what i know you cannot fo multi interface assignment on an VE..however what is puzzling is the error message..i will have to check it tomorrow morning my time on a VE image..

**Comment by payalsin** [comment] 2017-04-17 22:20
ahh yes you re right, cannot assign more than one interface on a VE.....

the error message I see on the UI is: 01070734:3: Configuration error: vmw-compat: vlan may only have one interface

Sure thanks fr checking, if you need to use my BIGIP for testing let me know...

**Comment by wojtek0806** [comment] 2017-04-18 08:50
I have run the test playbook against my VE and I have gotten this error, which is expected:

````

fatal: [192.168.165.142]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://192.168.165.142:443/mgmt/tm/net/vlan/\nText: u'{\"code\":400,\"message\":\"01070734:3: Configuration error: vmw-compat:  vlan may only have one interface\",\"errorStack\":[],\"apiError\":3}'"}
        to retry, use: --limit @/home/vagrant/ansible_test/test/integration/bigip_vlan.retry


````
As this is not reproducible on my VE,  this is most likely caused by some of the interfaces not returned in the REST call:

https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_vlan.py#L240

As I see no other way of this to break. Let me know if you have further questions, otherwise I will close this issue :)

**Comment by payalsin** [comment] 2017-04-18 15:09
I see interesting. Sure lets close it out. Can you do a GET on your interfaces just to compare if there is something different from your BIG-IP than from mine. thanks

**Comment by caphrim007** [comment] 2017-04-18 15:13
@payalsin I want @wojtek0806 to contact you offline and test directly against your BIG-IP to ensure that we're not missing something.

**Comment by wojtek0806** [comment] 2017-04-18 16:16
After OOB conversation, we have found this issue not reproducible anymore with the original VE. Removing quotes from interface names, has had no effect. Closing for now.

**Closed by wojtek0806** 2017-04-18 16:16 UTC

**Comment by mikeandretta** [comment] 2017-08-08 10:57
Was there any development on this? Im looking to use tagged_interface: Virtuals as my tagged interface for the newly created bigip_vlan. If I already have a trunk with interface 1.1 and 1.2 inside of it and I want to use the trunked "string" value on within the tagged_interface: why is this not an option?

Thanks!

**Comment by caphrim007** [comment] 2017-08-08 16:27
@mikeandretta nearly all dev happens on VEs, so it's likely that we just didnt test for this. @wojtek0806 you have metal you could repro this on, aye?

**Comment by caphrim007** [comment] 2017-08-09 19:36
@mikeandretta would you open a new issue to cover your question? Otherwise we will miss this comment and issue in the long term

**Comment by mikeandretta** [comment] 2017-08-09 20:03
@caphrim007 I will open a new ticket in the morning with the same information I have in the comment above for tracking. 

Thanks!

**Comment by wojtek0806** [comment] 2017-08-11 09:06
@caphrim007 I will take care of checking on hardware once i get from under water

**Comment by mikeandretta** [comment] 2017-08-11 09:45
@wojtek0806 @caphrim007 a new ticket was opened for this, please see below. 

If there is anything I can do to assist please let me know. 

https://github.com/F5Networks/f5-ansible/issues/304
