### ISSUE TITLE
bigip_device_httpd fails on first attempt, works on 2nd - new behavior

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1209] opened 2019-02-06 19:27 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_httpd

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4

##### SUMMARY

The first run when onboarding a new bigip device always fails with
```
msg: ''''''
```
##### STEPS TO REPRODUCE

```
See Onboard.yaml in Gist
```

https://gist.github.com/C0missar/dfb9f57841b886e1f7a4c271530b4e7b
##### EXPECTED RESULTS

```
Successful execution as shown in Onboard-QAb-worked.log in Gist
```
##### ACTUAL RESULTS

```
Execution failure on the bigip_httpd task as shown in Onboard-QAb-failed.log in Gist
```

**Comment by C0missar** [comment] 2019-02-06 19:29
This used to work consistently, but there have been numerous role updates over the last month, and I don't know exactly when this started.

**Comment by wojtek0806** [comment] 2019-02-07 21:25
This is most likely due to the BIGIP HTTPD daemon not being ready, can you consistently reproduce this issue on the same machine? or does this only happen when you boot up ?

**Comment by C0missar** [comment] 2019-02-07 21:31
I'll try it again, but it had been some time after boot on both images.  It seemed like it was the first attempt to change, rather than a timing issue.

If it is timing, what is the right way to detect that and wait?

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by wojtek0806** [comment] 2019-03-27 11:19
@C0missar you can use bigip_wait module to set some timeouts there is no set times I can provide due to a range of hardware/software combinations. If you can consistently reproduce this then I can have a look at and reopen this issue. Closing as not reproducible for now

**Closed** 2019-03-27 11:20 UTC
Labels: bug-report, not-reproducible

**Comment by C0missar** [comment] 2019-04-26 04:51
Please reopen this case.  This is very repeatable.  Attached is a GIST with a minimal playbook to demonstrate the problem, and two runs back to back.  It doesn't matter how much time elapses between device startup or between runs, the first always fails and all subsequent runs work.  I just updated the role yesterday; nothing has changed.

https://gist.github.com/C0missar/0af96822da4be09cb5ea51a520e4c7bb
