### ISSUE TITLE
bigip_iapp_template: "template error while templating string: tag name expected"

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#547] opened 2017-12-29 09:43 UTC
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME

bigip_iapp_template

##### ANSIBLE VERSION

Ansible Tower 3.1.5

```
(ansible)[root@rhel74-1-ucamaro vcpe]# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### PYTHON VERSION

```
(ansible)[root@rhel74-1-ucamaro ~]# python -V
Python 2.7.5

```

##### BIGIP VERSION

```
[root@bigip1:Eval:Active:Standalone] tmp # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       2.0.1671
  Edition     Hotfix HF2
  Date        Fri Apr 28 20:36:43 PDT 2017

```

##### LIBRARY VERSIONS

```
(ansible)[root@rhel74-1-ucamaro ~]# pip freeze | egrep '(f5-sdk|bigsuds)'
f5-sdk==3.0.4

```

##### CONFIGURATION

I'm using bigip_iapp_template from github (that is the latest version) rather than the one installed from ansible

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY

When loading a large iApp I get the following error:

```
TASK [add-customer-services : Add to the BIG-IP library the iApp file DNSTunnelMitigationV7.tmpl] ***
fatal: [10.105.211.111]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: tag name expected. String: cli admin-partitions {\n    update-partition Common\n}\nsys application template DNSTunnelMitigationV7 {\n    actions {\n        definition {\n            html-help {\n            }\n            implementation {\n
```

**Note: not all output shown**

The template is 66292 bytes in size. There is no log in /var/log/audit. The iApp loads properly when using tmsh load

Please drop me a note and I will send the iApp template and a role

Thanks

      Ulises

**Comment by delgadillo22** [comment] 2018-01-11 21:42
Corner case or common? (exposure level?)

**Comment by caphrim007** [comment] 2018-01-11 22:38
@delgadillo22 corner case. None of the F5 iApps on downloads raise this error (we test all of them)

**Comment by delgadillo22** [comment] 2018-01-15 19:12
Thanks, moving to LOW priority.

**Comment by caphrim007** [comment] 2018-11-15 02:54
closing this as I am unable to reproduce with the iapps that F5 publishes on downloads. You may want to try the most recent version of the modules as published in ansible galaxy here

https://galaxy.ansible.com/f5devcentral/f5ansible

**Closed by caphrim007** 2018-11-15 02:54 UTC
Labels: bug-report, low, synced
