### ISSUE TITLE
bigip_device_sshd not idempotent

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1181] opened 2019-01-25 01:52 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_sshd
bigip_device_auth_ldap

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4

##### SUMMARY

The listed modules are not idempotent.  A change is recorded on every invocation when no data is changed.

##### STEPS TO REPRODUCE

```
https://gist.github.com/C0missar/598ff2ffaf94d577c3a7324942bd2d60
```

https://gist.github.com/C0missar/d5e0aa8b1410cbcf4212230cbd3075a8
##### EXPECTED RESULTS

ok: [awsf5deva.sherwin.com]
ok: [awsf5deva.sherwin.com]

##### ACTUAL RESULTS

```
changed: [awsf5deva.sherwin.com]
changed: [awsf5deva.sherwin.com]
```

**Comment by wojtek0806** [comment] 2019-01-26 12:48
@C0missar The error log shows old bug in the role, can you update it please?

**Comment by wojtek0806** [comment] 2019-01-28 12:48
the import error you have means the role was not updated, as this was definitely fixed so you should be able to use the role

**Comment by C0missar** [comment] 2019-01-28 14:46
I provided the output showing that the role was definitely updated.  You mentioned deleting and reinstalling something; if you can provide instructions, I'll try it.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by wojtek0806** [comment] 2019-01-28 15:12
The output linked here:

https://gist.github.com/C0missar/d5e0aa8b1410cbcf4212230cbd3075a8

Does not show you installing the newest version of the role, it shows the attached playbook run and the resulting import error which indicates that when you ran this you have had old version of the f5ansible role installed, so this does not show us the idempotency issue you reported.

The other gist link seems related to #1182 you have opened:

https://gist.github.com/C0missar/598ff2ffaf94d577c3a7324942bd2d60#file-test-log-L139

which shows you using the f5 ansible role ok, meaning you must have updated it.

In short I need you to show me the idempotency failure with the role, or if this is already in one of your gists, simply point the line as I have looked at them few times and I cannot see where you see the idempotency problem

To answer second question to remove the role you just simply use ansible-galaxy to remove it:

https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#delete-a-role

On a side note I will be formulating some new requirements for the bug reports opened on GitHub, one of them will be running an issue test with the playbook that uses the role. So we can avoid duplication of work and reporting on problems already resolved in devel.

**Comment by wojtek0806** [comment] 2019-01-28 15:37
This issue title is: **bigip_device_sshd and bigip_device_auth_ldap not idempotent**

I already said looks like the role is updated, but the gists you linked here are not reflecting the idempotency problem with sshd and auth_ldap modules.


As far as other issues are concerned, it would be best if you replied to them one by one, as this gets confusing quickly.

**Comment by wojtek0806** [comment] 2019-01-29 00:36
So is the idempotency breaking is reflected in these tasks?

https://gist.github.com/C0missar/3f7ab7ed2cca7683d35086fe1e8af218#file-test-log-L75
https://gist.github.com/C0missar/3f7ab7ed2cca7683d35086fe1e8af218#file-test-log-L168

If so the second task which is the LDAP module will not be idempotent due to the following:

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_device_auth_ldap.py#L120

Looking at your log and yaml:

https://gist.github.com/C0missar/3f7ab7ed2cca7683d35086fe1e8af218#file-test-log-L213
https://gist.github.com/C0missar/3f7ab7ed2cca7683d35086fe1e8af218#file-test-yaml-L54

I will look into reproduction of the SSHD breakage locally

**Closed** 2019-03-27 11:21 UTC
Labels: bug-report, fails-on-devel, low
