### ISSUE TITLE
bigip_virtual_server: destination not properly validated for forwarding-ip virtual servers

### ISSUE THREAD

**Issue by c41m4n** [F5Networks/f5-ansible#970] opened 2018-10-01 23:53 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/calman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### PYTHON VERSION

```
Python 2.7.5

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### SUMMARY

When attempting to create a forwarding-ip virtual server the destination property can not be a network. Only single IP addresses as the destination allow the play to complete without errors.

As a workaround I specify just the IP of the network (in my example, 10.90.0.0) instead of the network itself (10.90.0.0/22).  This allows the play to complete then I manually add the CIDR via the GUI.  However when I do this then re-run the play it records no changes, despite the config specifying a /22 mask and the playbook listing a single IP as the destination.
##### STEPS TO REPRODUCE

```
---
- name: Test create forwarding VS
  connection: local
  hosts: localhost
  gather_facts: false

  vars:
        vcmp_provider:
                server: 1.2.3.4
                user: ansible
                password: "XXREDACTEDXX"
                validate_certs: false

  tasks:
        - name: Create inbound forwarding VS
          bigip_virtual_server:
                provider: "{{ vcmp_provider }}"
                state: present
                partition: Common
                name: "LOW-ITS-SYS-INBOUND-IPv4-FWD_VS"
                description: "Inbound VLAN 3400 traffic"
                source: 0.0.0.0/0
                port: 0
                # destination: 10.90.0.0
                destination: 10.90.0.0/22
                enabled_vlans: "DC"
                type: forwarding-ip
                firewall_enforced_policy: "LOW-ITS-OUTBOUNDv4_AFM_POLICY"
                profiles:
                        - fastL4_forwarding
          delegate_to: localhost

```

##### EXPECTED RESULTS

I expected the VS to be created with 10.90.0.0/22 as destination.
##### ACTUAL RESULTS

```
$ [0] ansible-playbook -vvvv f5-create-forwarding-vs.yml --vault-password-file ~/ansible-f5/.ansible_vault
ansible-playbook 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/calman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin yaml of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/yaml.pyc

PLAYBOOK: f5-create-forwarding-vs.yml *******************************************************************************************************************************************************************************************************
1 plays in f5-create-forwarding-vs.yml

PLAY [Test create forwarding VS] ************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create inbound forwarding VS] *********************************************************************************************************************************************************************************************************
task path: /home/calman/ansible-f5/f5-create-forwarding-vs.yml:15
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: calman
<localhost> EXEC /bin/sh -c 'echo ~calman && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398 `" && echo ansible-tmp-1538436629.13-192503715594398="` echo /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> PUT /home/calman/.ansible/tmp/ansible-local-8876rT2fDG/tmp25NjR5 TO /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398/bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398/ /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398/bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398/bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/calman/.ansible/tmp/ansible-tmp-1538436629.13-192503715594398/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 2728, in main
    results = mm.exec_module()
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 2499, in exec_module
    changed = self.present()
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 2515, in present
    return self.create()
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 2587, in create
    validator.check_create()
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 1750, in check_create
    self._verify_virtual_has_required_parameters()
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 1948, in _verify_virtual_has_required_parameters
    if all(getattr(self.want, v) is None for v in required_resources):
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 1948, in <genexpr>
    if all(getattr(self.want, v) is None for v in required_resources):
  File "/tmp/ansible_nmllr8/ansible_module_bigip_virtual_server.py", line 1246, in destination
    "The provided destination is not a valid IP address"

fatal: [localhost -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      address_translation: null
      default_persistence_profile: null
      description: Inbound VLAN 3400 traffic
      destination: 10.90.0.0/22
      disabled_vlans: null
      enabled_vlans:
      - '3420'
      fallback_persistence_profile: null
      firewall_enforced_policy: LOW-ITS-OUTBOUNDv4_AFM_POLICY
      firewall_staged_policy: null
      ip_protocol: null
      irules: null
      metadata: null
      name: LOW-ITS-SYS-INBOUND-IPv4-FWD_VS
      partition: Common
      password: null
      policies: null
      pool: null
      port: '0'
      port_translation: null
      profiles:
      - fastL4_forwarding
      provider:
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: 10.100.32.51
        server_port: null
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: ansible
        validate_certs: false
      security_log_profiles: null
      server: null
      server_port: null
      snat: null
      source: 0.0.0.0/0
      state: present
      transport: null
      type: forwarding-ip
      user: null
      validate_certs: null
  msg: The provided destination is not a valid IP address
        to retry, use: --limit @/home/calman/ansible-f5/f5-create-forwarding-vs.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by caphrim007** [comment] 2018-10-02 18:33
@c41m4n i believe this is a duplicate of #650. Can you check to see if this other issue addresses your request?

**Comment by c41m4n** [comment] 2018-10-03 16:13
@caphrim007 this does look like a duplicate.  My search-fu failed me.

**Comment by caphrim007** [comment] 2018-10-03 16:56
@c41m4n okie doke. no problem. Do you want to go over there and click the smiley face button on the initial comment and give it an emoticon of some sort so that we know you're interested?

**Closed** 2018-10-03 16:56 UTC
