### ISSUE TITLE
Failed to download UCS. Missing Content-Range header

### ISSUE THREAD

**Issue by ivansr93** [F5Networks/f5-ansible#2044] opened 2021-06-03 14:25 UTC
##### COMPONENT NAME
bigip_ucs_fetch

##### ANSIBLE VERSION

```
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /data/venv/lib/python3.8/site-packages/ansible
  executable location = /data/venv/bin/ansible
  python version = 3.8.6 (default, Oct  7 2020, 14:58:56) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.2.1
  Build       0.0.10
  Edition     Point Release 1
  Date        Fri Jan 15 13:43:15 PST 2021
```
##### CONFIGURATION

I am using f5networks.f5_modules 1.9.2-devel

##### OS / ENVIRONMENT

RHEL 7.9

##### SUMMARY

I am receiving a module error with traceback exception KeyError: 'Content-Range' when trying to fetch a UCS file from device.

##### STEPS TO REPRODUCE

```
  - name: "[F5] | Download UCS file file"
    bigip_ucs_fetch:
      src:  "{{ filename_f5 }}"
      dest: "{{ folder_destination }}/{{ filename_f5 }}"
      create_on_missing: yes
      provider: "{{ f5_provider }}"
    register: download_new_ucs
```

##### EXPECTED RESULTS

Downloading UCS file to save inside a local machine.
##### ACTUAL RESULTS

```
TASK [backups : [F5] | Download UCS file file] *******************************************************************************************************
task path: /home/<user>/bs2cloud-network/roles/backups/tasks/create-backup-f5-device.yml:52
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
Loading collection ansible.netcommon from /home/<user>/collections/ansible_collections/ansible/netcommon
<127.0.0.1> connection transport is rest
<127.0.0.1> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<127.0.0.1> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: <user>
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp `"&& mkdir "` echo /tmp/ansible-tmp-1622730245.063577-12007-106100769666546 `" && echo ansible-tmp-1622730245.063577-12007-106100769666546="` echo /tmp/ansible-tmp-1622730245.063577-12007-106100769666546 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.bigip_ucs_fetch to f5networks.f5_modules.bigip_ucs_fetch
Using module file /home/<user>/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py
<127.0.0.1> PUT /tmp/ansible-local-11750944ardam/tmphrwq6_6x TO /tmp/ansible-tmp-1622730245.063577-12007-106100769666546/AnsiballZ_bigip_ucs_fetch.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1622730245.063577-12007-106100769666546/ /tmp/ansible-tmp-1622730245.063577-12007-106100769666546/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/data/venv/bin/python /tmp/ansible-tmp-1622730245.063577-12007-106100769666546/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1622730245.063577-12007-106100769666546/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1622730245.063577-12007-106100769666546/AnsiballZ_bigip_ucs_fetch.py", line 102, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1622730245.063577-12007-106100769666546/AnsiballZ_bigip_ucs_fetch.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1622730245.063577-12007-106100769666546/AnsiballZ_bigip_ucs_fetch.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ucs_fetch', init_globals=None, run_name='__main__', alter_sys=True)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 679, in <module>
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 672, in main
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 277, in exec_module
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 314, in exec_module
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 327, in present
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 385, in create
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 346, in execute
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 465, in download
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 614, in download_from_device
  File "/tmp/ansible_bigip_ucs_fetch_payload_39p8s4r8/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 404, in download_file
KeyError: 'Content-Range'
```

**Comment by trinaths** [comment] 2021-06-16 21:59
@ivansr93 I was not able to reproduce this issue. 

Tried with latest devel. A pre generated UCS file is downloaded to the destination folder.

My playbook and output.

```
  tasks:
  - name: "[F5] | Download UCS file file"
    bigip_ucs_fetch:
      src:  "{{ filename_f5 }}"
      dest: "{{ folder_destination }}/{{ filename_f5 }}"
      create_on_missing: yes
      provider: "{{ provider }}"
    register: download_new_ucs

-- output

ansible-playbook 2.10.7
  config file = None
  configured module search path = ['/Users/tsomanchi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tsomanchi/ansible/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/tsomanchi/ansible/ansible/bin/ansible-playbook
  python version = 3.7.3 (default, Mar  6 2020, 22:34:30) [Clang 11.0.3 (clang-1103.0.32.29)]


PLAYBOOK: playbook.yaml ********************************************************************************************************************************************************************************************************************************************************
1 plays in playbook.yaml

PLAY [demo lab] ****************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [[F5] | Download UCS file file] *******************************************************************************************************************************************************************************************************************************************
task path: /Users/tsomanchi/ansible/f5-ansible-solutions/github/2044/playbook.yaml:21
<XXXXXXXX> ESTABLISH LOCAL CONNECTION FOR USER: tsomanchi
<XXXXXXXX> EXEC /bin/sh -c 'echo ~tsomanchi && sleep 0'
<XXXXXXXX> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/tsomanchi/.ansible/tmp `"&& mkdir "` echo /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948 `" && echo ansible-tmp-1623880318.110815-30692-210297143878948="` echo /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948 `" ) && sleep 0'
Using module file /Users/tsomanchi/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py
<XXXXXXXX> PUT /Users/tsomanchi/.ansible/tmp/ansible-local-30688qmhp17wf/tmp9q8t2onf TO /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948/AnsiballZ_bigip_ucs_fetch.py
<XXXXXXXX> EXEC /bin/sh -c 'chmod u+x /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948/ /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<1XXXXXXXX> EXEC /bin/sh -c '/Users/tsomanchi/ansible/ansible/bin/python3 /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<XXXXXXXX> EXEC /bin/sh -c 'rm -f -r /Users/tsomanchi/.ansible/tmp/ansible-tmp-1623880318.110815-30692-210297143878948/ > /dev/null 2>&1 && sleep 0'
changed: [bigip] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "async_timeout": 150,
            "attributes": null,
            "backup": false,
            "create_on_missing": true,
            "dest": "/tmp/testucs.ucs",
            "encryption_password": null,
            "fail_on_missing": false,
            "force": true,
            "group": null,
            "mode": null,
            "owner": null,
            "provider": {
                "auth_provider": null,
                "no_f5_teem": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "XXXXXXXXXX",
                "server_port": 443,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "testucs.ucs",
            "unsafe_writes": false
        }
    },
    "src": "jjwv2r99.ucs"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
bigip                      : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

What would be the size of UCS? can you reinstall latest devel and retry ?

**Comment by KrithikaChidambaram** [comment] 2022-11-30 17:54
Closing this now. Reopen if you still face the issue. Thanks!

**Closed by KrithikaChidambaram** 2022-11-30 17:54 UTC
Labels: awaiting-user-action, In Review

**Comment by grmenon** [comment] 2023-09-14 20:19
I was running into this very issue & here is how I fixed it. My backup is approx 700MB. The way I fixed it was to add "async_timeout: 1800" option to the "bigip_ucs_fetch" task. Here is how the playbook looks like
```
        - name: Fetch backup from device
          f5networks.f5_modules.bigip_ucs_fetch:
            provider: "{{ provider }}"
            create_on_missing: false
            dest: "{{bkup_path}}/{{shortName}}_{{runDate}}.ucs"
            async_timeout: 1800
```
I am creating the backup in a previous step.
