### ISSUE TITLE
bigip_software_install - [ValueError: AbstractDigestAuthHandler does not support the following scheme: 'X-Auth-Token']

### ISSUE THREAD

**Issue by hazelfire5** [F5Networks/f5-ansible#1798] opened 2020-07-20 22:30 UTC
No issue reported that is similar.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_software_install

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.10
  config file = /Users/hazel/src/f5-toolbox/ansible.cfg
  configured module search path = ['/Users/hazel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/hazel/src/f5-toolbox/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/hazel/src/f5-toolbox/venv/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### PYTHON VERSION

```
$ python -V
Python 3.7.4
```

##### BIGIP VERSION

```
# show sys version 

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using the module **bigip_software_install**, I get this issue.
```

```
##### STEPS TO REPRODUCE

I have narrowed it down to something to do with the transport being set to `rest`. When I set the transport to `rest` on the **bigip_command** task, I get the same **ValueError** issue. Once I set it to `cli`, the task executes normally. I tried to set `cli` to the **bigip_software_install** task and that outputs a `ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'set_cli_prompt_context'`.  I couldn't find anyone else with this issue so I am thinking this is a step I missed somewhere? How do we get this playbook to execute correctly?
```
---
- name: BIG-IP SETUP
  hosts: f5node1
  connection: local
  collections:
    - f5networks.f5_module
  tasks:
  - name: run show version on remote devices
    bigip_command:
      commands: show sys version
      provider: 
        password: "{{ ansible_ssh_pass }}"
        server: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        validate_certs: no
        transport: cli
    delegate_to: localhost
    register: facts_result

  - name: Display the results
    debug:
      var: facts_result

  - name: Ensure an existing image is installed in specified volume
    bigip_software_install:
      image: BIGIP-13.0.0.0.0.1645.iso
      volume: HD1.2
      state: installed
      provider: 
        password: "{{ ansible_ssh_pass }}"
        server: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        validate_certs: no
        transport: rest
    delegate_to: localhost

```

##### EXPECTED RESULTS
For task to execute and ensure the image is installed in a specific volume.

##### ACTUAL RESULTS

Playbook errors out and fails. 

```
TASK [Ensure an existing image is installed in specified volume] ****************************************
task path: /Users/hazel/src/f5-toolbox/bigip-virtual-server-sw-check-upgrade.yml:24
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: hazel
<localhost> EXEC /bin/sh -c 'echo ~hazel && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/hazel/.ansible/tmp `"&& mkdir /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036 && echo ansible-tmp-1595283996.111962-13077-206162148507036="` echo /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036 `" ) && sleep 0'
Using module file /Users/hazel/src/f5-toolbox/venv/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_software_install.py
<localhost> PUT /Users/hazel/.ansible/tmp/ansible-local-12889d5hffi0r/tmp465_mnov TO /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/ /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/hazel/src/f5-toolbox/venv/bin/python3 /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_software_install', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 523, in <module>
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 516, in main
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 297, in exec_module
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 315, in present
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 333, in exists
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py", line 36, in api
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py", line 86, in connect_via_basic_auth
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 232, in get
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 193, in send
  File "/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1027, in http_error_401
    url, req, headers)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 980, in http_error_auth_reqed
    return self.retry_http_basic_auth(host, req, realm)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 990, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1091, in http_error_auth_reqed
    " the following scheme: '%s'" % scheme)
ValueError: AbstractDigestAuthHandler does not support the following scheme: 'X-Auth-Token'
fatal: [eva1nvmba01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/hazel/.ansible/tmp/ansible-tmp-1595283996.111962-13077-206162148507036/AnsiballZ_bigip_software_install.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_software_install', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 523, in <module>\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 516, in main\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 297, in exec_module\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 315, in present\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 333, in exists\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 36, in api\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 86, in connect_via_basic_auth\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 232, in get\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 193, in send\n  File \"/var/folders/2m/rl69kp354jv05hnsnb64zgch0000gq/T/ansible_bigip_software_install_payload_fc203ql5/ansible_bigip_software_install_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 563, in error\n    result = self._call_chain(*args)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 1027, in http_error_401\n    url, req, headers)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 980, in http_error_auth_reqed\n    return self.retry_http_basic_auth(host, req, realm)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 990, in retry_http_basic_auth\n    return self.parent.open(req, timeout=req.timeout)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 563, in error\n    result = self._call_chain(*args)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 1207, in http_error_401\n    host, req, headers)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 1091, in http_error_auth_reqed\n    \" the following scheme: '%s'\" % scheme)\nValueError: AbstractDigestAuthHandler does not support the following scheme: 'X-Auth-Token'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by grubino** [comment] 2021-02-12 19:07
I have the same issue... it suddenly started happening when I was testing a playbook

**Comment by focrensh** [comment] 2021-02-12 19:21
I can confirm that transport CLI should not work. This module currently only supports REST. @hazelfire5 , have you tried this with our newest Collection version to see if this is resolved? I have tested 12 >> 13 in an env and seems to be working.

@grubino , What environment do you have setup? which collection version, python version, source BIG-IP version, destination BIG-IP version?

**Comment by grubino** [comment] 2021-02-12 19:32
interesting... I am using the REST transport... 

collection version: 1.7.1
python version: 3.9

This error is actually occurring for every f5_modules ansible module that I'm executing with the REST transport, but I'm using this particular module as well, and my source and dest versions are 15.1.1 => 15.1.2

Ansible version is 2.10 in case that's relevant.

**Comment by janrv** [comment] 2021-03-12 08:54
I'm experiencing the same problem.
We did an upgrade last night from version 15.1.0.4 to 15.1.2.1 on the LTMs and since then all F5 ansible modules are failing with 
AbstractDigestAuthHandler does not support the following scheme: 'X-Auth-Token'

**Comment by janrv** [comment] 2021-03-12 12:59
> 
> 
> I'm experiencing the same problem.
> We did an upgrade last night from version 15.1.0.4 to 15.1.2.1 on the LTMs and since then all F5 ansible modules are failing with
> AbstractDigestAuthHandler does not support the following scheme: 'X-Auth-Token'
> 
> We are using the rest transport:
> 
> provider:
> user: "{{ ansible_ssh_user }}"
> password: "{{ ansible_ssh_password }}"
> validate_certs: no
> server: "{{ansible_host}}"
> transport: rest
> timeout: 6000
> 
>     * name: Get the virtual servers on the LTM
>       vars:
>       ansible_command_timeout: 600
>       bigip_device_info:
>       gather_subset: virtual-servers
>       provider: "{{ provider }}"
>       register: virtualservers
>       retries: 10
>       delay: 100
>       until: virtualservers is not failed
> 
> 
> Ansible version: 2.9.13
> Python version: 3.6.8

I seem to have found a solution for my issue. It seems that upgrading to this new f5 version changes the nas identifier for radius authentication. It is now using nas-id: 'rest' which we didn't have configured on our nps policy. After adding this, the error is now gone.

**Comment by narasims** [comment] 2021-03-15 00:18
I experienced this issue on one of the appliance. when the transport was rest. But it got fixed after a reboot.

**Comment by DerrickTJ** [comment] 2021-03-17 16:32
I also had X-Auth-Token error after performing an upgrade on one of my F5s. As suggested above, rebooting it fixed it.

Tried just restarting httpd and tomcat but that didn't do anything.

**Comment by trinaths** [comment] 2022-02-16 09:13
Its a issue at the ReST api and not an issue with ansible module. Closing this issue.

**Closed by trinaths** 2022-02-16 09:13 UTC
